### ISSUE TITLE
Link validation when sending no longer recognizes valid, 302 responses

### ISSUE THREAD

**Issue by WyrdByWord** [buttondown/roadmap#1297]
I use a link shortener as a reflector in my newsletters to combat link rot over time.

Recently, when sending a message, Buttondown started reporting those links as broken. This prompted me to investigate on my end and I realized I should be sending a 302 response for those links. I set that up and those links were noted as valid again.

Today, the same problem has reappeared. But I am loath to revert from what I think is the correct 302 response, since I do find the Buttondown check before sending valuable!

**Comment by jmduke** [comment]
@WyrdByWord Can you share an example URL?

**Comment by WyrdByWord** [comment]
Sure. These are two that were noted as invalid when scheduled this morning.

- https://wyrdbyword.xyz/l/ploughshares
- https://wyrdbyword.xyz/l/ploughshares-spring-2004

Though I realize now that there is a third that wasn't noted as a problem, so perhaps there's something else going on.

**Comment by jmduke** [comment]
Very interesting — looks like I'm having issues following HTTPS through the redirect

![image](https://user-images.githubusercontent.com/461046/227628984-45f7b15b-3a18-447c-94fc-6b263244b0bf.png)

**Comment by jmduke** [comment]
OOC: what are you using as a link shortener?

**Comment by WyrdByWord** [comment]
[YOURLS](https://github.com/YOURLS/YOURLS) 1.9.1 (1.9.2 released recently, but I haven't had time to upgrade)!
