### ISSUE TITLE
“Scaffolding” for /username and /username/archive pages

### ISSUE THREAD

**Issue by benborgers** [buttondown/roadmap#1551]
Currently you can add headers/footers/CSS to the archived emails themselves, but not the other pages: `/username` and `/username/archive`.

**Comment by Mjr6891** [comment]
I'm new to this I'm looking for a user 
Sareve2889

**Comment by jmduke** [comment]
Note that this needs to dovetail with the new design for these pages launching as part of https://github.com/buttondown-email/roadmap/issues/1623.

See below:

![image](https://github.com/buttondown-email/roadmap/assets/461046/da8aa77a-2fbc-45ab-ac30-52585db438c1)
