### ISSUE TITLE
Markdown parsing and em/en-dashes

### ISSUE THREAD

**Issue by WyrdByWord** [buttondown/roadmap#1639]
Did something change with the Markdown parser? Until a week or so ago, `---` rendered as an em-dash in the resulting email (except on a line by itself where it is rendered as a rule.

That is no longer happening. 

Nor does it appear that `--` is rendering as an en-dash anywhere, which is also a change.

I can adjust by using the Unicode characters, but I figured I would ask, since it was frustrating to discover the change belatedly by noticing the non-rendered text.

**Comment by jmduke** [comment]
Oh! Yes. I turned off smart-enabling to fix some odd issues with template tagging; the goal was to remove auto smart-quoting but not em-dashing. Will re-enable this.

**Comment by WyrdByWord** [comment]
Ah, that makes sense. Good to know about the smart-quoting too, though!

**Comment by WyrdByWord** [comment]
BTW: does this mean smart-quoting won't be coming back?
