### ISSUE TITLE
Emails sometimes render in dark mode as dark-on-dark

### ISSUE THREAD

**Issue by benborgers** [buttondown/roadmap#1688]
This is a combination of #1157, #1159, and #1338. 

This [is solved](https://docs.google.com/document/d/1VA2J9ntwIL6BLsqB6KgbaLIiNno85hAk52ofCZRKlhc) by the `white_background` flag, which adds `background-color: white` to emails, but that change hasn’t been fully tested in all email clients so it’s hard to know whether there’s a regression somewhere.

**Comment by jmduke** [comment]
@benborgers What's the state of this? Do we want to keep this as a flag or promote it to GA?
