### ISSUE TITLE
Feedback on Safari Theme Color

### ISSUE THREAD

**Issue by eannichine** [buttondown/roadmap#1728]
"it’d be great if the color on Safari tab/toolbar could match the white background instead of blue"

<img width="540" alt="Screen Shot 2023-07-24 at 11 39 02 AM" src="https://github.com/buttondown-email/roadmap/assets/140091930/d18ac7ca-7e8f-42b1-8493-820a8da85cfd">
<img width="298" alt="Screen Shot 2023-07-24 at 11 39 27 AM" src="https://github.com/buttondown-email/roadmap/assets/140091930/23baaf44-7bb0-47fb-8689-d21c83ba799e">

**Comment by jmduke** [comment]
Should be self-explanatory!
