### ISSUE TITLE
Allow anchoring automation timing to a specific day of week

### ISSUE THREAD

**Issue by jmduke** [buttondown/roadmap#1766]
- [x] Time of day anchoring
- [ ] Time of week anchoring

**Comment by efletch** [comment]
[HelpScout Mention](https://secure.helpscout.net/conversation/2318849452/1200)

**Comment by efletch** [comment]
Follow up from customer about use case: _"What I'd really love is being able to customize the time zone and hour (because as my audience is American, ideally I'd send these emails at 8am Central Standard Time (CST) so they had something positive to start their day with.)"_

**Comment by jmduke** [comment]
@efletch Can you ask them if they have their personal time zone set to CST? If so, this should do exactly what they expect/want!
