### ISSUE TITLE
Move Restore button in History modal to top

### ISSUE THREAD

**Issue by benborgers** [buttondown/roadmap#1852]
In its current position at the bottom, it can get hidden if there's lots of history. 

Maybe it'd avoid some confusion if moved to the top and labeled "Restore selected version"? 

<img width="1470" alt="2023-08-28 at 08 02 27@2x" src="https://github.com/buttondown-email/roadmap/assets/30215449/3765e4f4-f7d3-438b-a3f2-e55238e83e96">

https://secure.helpscout.net/conversation/2330377190/1270?folderId=7407077

**Comment by jmduke** [comment]
Closing in favor of https://github.com/buttondown/roadmap/issues/2388.
