### ISSUE TITLE
`/features` has some weird scrolling behavior on mobile

### ISSUE THREAD

**Issue by jmduke** [buttondown/roadmap#1930]

**Comment by zeucapua** [comment]
@jmduke are there anything specific about this page that's "weird"? checked on my phone and on mobile view in browser and it seems fine.

**Comment by jmduke** [comment]
@zeucapua smh this is why I need to do a better job writing roadmap items. I think the only thing I'm seeing right now that's still reproducable is the ability to "scroll" animations like the one for `Write in markdown` — that shouldn't be possible, so if we can maintain that little animation effect while not hijacking the scroll event that'd be great.

**Comment by jmduke** [comment]
Closing this out as we're redoing this page soon-ish anyway.
