### ISSUE TITLE
Display more details about why webhook failed

### ISSUE THREAD

**Issue by benborgers** [buttondown/roadmap#1953]
Maybe the response body of the external system? 

https://secure.helpscout.net/conversation/2387114174/1647

**Comment by jmduke** [comment]
Very similar to #3319 — if a given webhook attempt has a failure, let's surface the JSON response in the UI.

**Comment by catdevnull** [comment]
![Screenshot 2024-09-02 at 7 36 45 PM](https://github.com/user-attachments/assets/331e2ce9-bf49-49c1-a8b7-004e5a4b80cb)
would be nice to add to each row a little icon showing if the last attempt failed or not
