### ISSUE TITLE
Slightly de-randomize attachment names

### ISSUE THREAD

**Issue by benborgers** [buttondown/roadmap#2034]
![Image](https://imagedelivery.net/e-7XlqFChXQT3gkuhGdYEQ/d7a1619a-5f56-42d1-7dbd-2e7183db9e00/public?ow=557&oh=225)
Attachments come through as `attachments/[uuid]`, which might look kinda suspicious. Perhaps it could be `attachments/[uuid]-original-file-name.` 

https://secure.helpscout.net/conversation/2409503728/1791

**Comment by jmduke** [comment]
@benborgers What are your thoughts on doing the same thing we do for slugs (keep the OG if possible, and then add a uuid-ish suffix if there's a collision)?

**Comment by benborgers** [comment]
The only thing that feels a little weird to me is that one person will get `attachments/download.pdf` (or any other common filename). I'm not sure whether it also opens it up to people guessing filenames in Buttondown's S3? But also not sure if that's a huge deal.

**Comment by dlwoda** [comment]
Another user wrote in requesting this - https://secure.helpscout.net/conversation/2519643990/3296?folderId=8083960

**Comment by jmduke** [comment]
Yup. I think we can have the same behavior we use in slug creation for emails: "default to the existing username, then add a suffix if there's a collision."

**Comment by benborgers** [comment]
I am a tiny bit skeptical just because having someone be "the canonical" `download.pdf` or `file.pdf` feels iffy

**Comment by benborgers** [comment]
I can get behind that!

`benborgers-results-chart.pdf`, then `benborgers-results-chart-s90n.pdf`, etc
