### ISSUE TITLE
sent-email counter broke, security policy exception

### ISSUE THREAD

**Issue by james-baker** [buttondown/roadmap#2060]
After sending an issue
On the "completed" your-email-is-sending/sent dialog:
The counter is staying at 0/N, and
This exception is firing about 3 times a second:
Uncaught DOMException: An attempt was made to break through the security policy of the user agent.
    at Pe (https://buttondown.email/static/base-4954ef9e.js:36:28151)
    at th.get (https://buttondown.email/static/base-4954ef9e.js:36:23620)
    at Object.get (https://buttondown.email/static/base-4954ef9e.js:36:51424)
    at https://buttondown.email/static/main-bb9b30d3.js:204:37105
    at i (https://buttondown.email/static/base-4954ef9e.js:16:16401)
i @ helpers.js:92

Chrome 118.0.5993.120 on Windows

**Comment by jmduke** [comment]
@james-baker Will take a look, but — do you have any extensions installed?

**Comment by james-baker** [comment]
Good question - this chrome profile has only "Google Docs Offline" installed. No ad blocker or other extensions.

**Comment by jmduke** [comment]
Bizarre, but thanks for confirming!

**Comment by james-baker** [comment]
More info: This time it did NOT keep the sent counter from incrementing. Also, it's not tied specifically to the polling loop because after I closed the post-sending modal, it kept going:
![image](https://github.com/buttondown-email/roadmap/assets/89615/801d9bc5-be1b-497d-8a06-172260fe43cc)
(that red 12000 is how many times it fired before I came back and noticed)

**Comment by james-baker** [comment]
(potential red herring alert) The status in the "completed" polling changes to "status": "sent" (and it arrives in my inbox) before any of the "analytics" polling numbers (like "deliveries") start incrementing. And today no analytics numbers are non-zero at all, ten minutes after the emails were actually sent.

**Comment by james-baker** [comment]
FWIW I did *not* see this exception today. ¯\_(ツ)_/¯

**Comment by jmduke** [comment]
I believe this is now fixed!
