### ISSUE TITLE
Onboard onto Redocly's OpenAPI linter

### ISSUE THREAD

**Issue by jmduke** [buttondown/roadmap#2136]

**Comment by jmduke** [comment]
Or potentially https://redocly.com/docs/cli/.

**Comment by jmduke** [comment]
@catdevnull Same with this one :) Let's start linting to make sure that, e.g., we're always adding descriptions and examples to new fields, that sort of thing.

**Comment by catdevnull** [comment]
I've implemented the linter and fixed the errors, but the CLI is failing with warnings and I can't seem to find info on how to make it not fail on warnings. `--help` doesn't work and I couldn't find info in the Konfig docs about it. Do we have a contact at Konfig?

**Comment by jmduke** [comment]
Hmm, I didn't realize it was closed-source; is it a huge lift to go with Redocly instead? (It feels unwise to have OAS be load-bearing on a closed-source linter by an early-stage co.)

**Comment by catdevnull** [comment]
Nope, on it
