### ISSUE TITLE
Exports need some sort of checkpointing or performance improvement

### ISSUE THREAD

**Issue by jmduke** [buttondown/roadmap#2226]

**Comment by ifpingram** [comment]
Justin, is it possible to also add a list of previous exports, like there was previously. I am not the master account email, and share the login to admin the system, but when I request an export of subscribers, it says it is taking too long and that it will email when ready. I never see these emails and cannot keep asking David to send them to me when he sees them. If there was a way to just list previous exports for download, this would avoid the issue, where I am unable to get access to an export of the subscribers, which I need to do some affiliate reconciliation.

Thanks!

**Comment by jmduke** [comment]
I think this is solved now! It's still not efficient, but we haven't had any stuck exports in a few months.
