### ISSUE TITLE
Fix broken changelog index

### ISSUE THREAD

**Issue by zeucapua** [buttondown/roadmap#2259]
Looks like when we landed the change we added a "tags" column to `/changelog`: can we fix that?

https://buttondown.email/changelog

**Comment by zeucapua** [comment]
@jmduke would you like me to remove the tags column altogether?

**Comment by zeucapua** [comment]
also I accidentally turned this into an issue and I cannot assign myself, apologies @jmduke

**Comment by jmduke** [comment]
@zeucapua 😂 bothers me that GitHub would let you convert an issue but not assign one.... seems weird

Yeah, we can remove it for now
