### ISSUE TITLE
Unable to get accurate affiliate referral payments

### ISSUE THREAD

**Issue by ifpingram** [buttondown/roadmap#2271]
We pay affiliates a commission for paying subscribers, which includes year 2+ renewal subscriptions. To try to work out this list of payments from which to pay commission, I can only access the full data via the list of subscribers. However, when somebody renews after a year, their subscription creation date remains the first payment, which is correct, however, this makes it very difficult to see from the subscriber list whether the person has continued their subscription or not. The subscribers list is thus great for getting numbers and details of first time subscribers, but not renewals.

I have seen that there is a count of Paid Subscribers in the Analytics section, aggregated by UTM. Is this what I am looking for? Does this number accurately reflect all the payments made by subscribers under the UTM within this time period? Does this include new first time subscribers and also renewal subscriber payments?

Thanks!

**Comment by jmduke** [comment]
@ifpingram Help me understand a little: is there a reason the full export and then "finding everyone marked as a premium subscriber whose premium start date is > 1 year ago" doesn't work?

**Comment by ifpingram** [comment]
I can't get the exports to work. See my comment at https://github.com/buttondown-email/roadmap/issues/2226

We reconcile quarterly, and if I could get access to the exports, then I could perhaps do what you are suggesting. If I can have access to the subscriber details then I can cross reference them on a quarterly basis. Hopefully it would work.

**Comment by jmduke** [comment]
Ah I should have clarified: I meant _if_ the exports did work and went to you.

How do you identify who is/isn't an affiliate-borne subscriber?

**Comment by ifpingram** [comment]
By their UTM.

**Comment by ifpingram** [comment]
Hi Justin

Sorry I never got back to you about the export you sent me. It wasn't really suitable, but in any case, do not worry about any of this, or my issue above. I have managed to get exactly what I need from the Stripe payments. This has everything including things like fees and refunds. It is not worth you trying to replicate this, as it will be a waste of your time.

Thanks. You can close the issue.
