### ISSUE TITLE
weird error experience

### ISSUE THREAD

**Issue by james-baker** [buttondown/roadmap#2292]
I was typing in the markdown editor as usual a few minutes ago, building out an email, when all of a sudden this popped up:
![image](https://github.com/buttondown-email/roadmap/assets/89615/d46c5433-56ba-403f-908d-9ac8b0743831)
There was nothing special about the series of keystrokes preceding the error.

Expected: Any error says what kind of error it is
Actual: No hint, not even "unknown"

Expected: If this dialog shows up, the X should close it.
Actual: Despite having some kind of focus indicator (that did go away when I clicked elsewhere on the dialog), and a clickable-looking mouse-cursor, the top-right "X" was unresponsive.

Clicking outside the dialog did dismiss it. No exceptions visible post-facto in the Chrome console. (Well, other than my "Uncaught DOMException: An attempt was made to break through the security policy of the user agent." which seems specific to my browser, happens all the time, and AFAIK isn't having any effect. But it could be relevant here.)

No repro known, filing FYI.

**Comment by jmduke** [comment]
@james-baker Can you share the email ID? I should be able to pull up what the actual error is.

**Comment by james-baker** [comment]
9274f22b-935a-4931-b430-1ba725f351e9

**Comment by james-baker** [comment]
Just experienced this again, 10-15 minutes ago, on e83291eb-a4d9-4476-bd8a-414b7fe25e24
