### ISSUE TITLE
Settings page toolbar is off the screen on iPad Safari

### ISSUE THREAD

**Issue by benborgers** [buttondown/roadmap#2322]
This probably applies to other bottom-fixed things as well? 

Might be a matter of using `svh` units or such?

https://secure.helpscout.net/conversation/2483507456/2681

**Comment by matthieugd** [comment]
Here’s a screenshot in a more « real life » scenario (i.e. iPad with Magic Keyboard)
<img width="1389" alt="image" src="https://github.com/buttondown-email/roadmap/assets/143315/c975fe29-108a-4f20-aec0-184fe4d56dcb">
