### ISSUE TITLE
editing email subject often loses typed characters

### ISSUE THREAD

**Issue by james-baker** [buttondown/roadmap#2431]
(didn't find a dupe in my searching, doesn't mean there isn't one)
After losing a couple letters, as is common, while typing my email subject, I decided to take a look.

This is my story about what's happening:
Some delay after last keypress, the UI issues a fetch (to the email object's URL, AFAICT) with all object data in the payload.
That fetch is taking about 1.0 - 1.1 seconds to return for me right now.
The response includes a "subject" that is the same thing that was sent a second ago.
Then, the UI replaces the email subject with what it received from the backend.

The trouble is, I often type some characters inside that 1-second round-trip time. Those characters get dropped when the subject gets replaced. Then if I'm lucky I notice the "blink" change right away, or else I keep typing and find the malformed word or punctuation upon later re-read.

It'd be nice if that stopped happening entirely. Is there something quirky about my typing speed or cadence that makes me more susceptible to this? I don't know. Seems like it'd be affecting a lot of people.

**Comment by jmduke** [comment]
@james-baker Checking in here — have you seen this in the past month or so? I think this got fixed alongside #2611.

**Comment by james-baker** [comment]
I have not, but also I have adopted defensive typing habits to try to avoid it. So, I will try to drop those, just type normally, and verify that this is fixed.
