### ISSUE TITLE
Clearing email description doesn't regenerate HTML

### ISSUE THREAD

**Issue by benborgers** [buttondown/roadmap#2440]
Anecdotally, if I:

1. Set email description to "asdf" and save
2. See that the short_email_description in the archives has changed
3. Go back and clear the email description and save
4. The short_email_description in the archives is still "asdf"

However, if I call `update_html` manually, the description goes back to the correct text. My suspicion is that `update_html` isn't being called when the input is cleared? Not sure though.

**Comment by jmduke** [comment]
@benborgers To clarify for #1 — are you sure you didn't also change the body of the email? Reading the logic for `update_html`, it looks like it only re-sets the `rendered_short_description` if the html_for_web changed — which accounts for 4., but doesn't account for 2.

**Comment by benborgers** [comment]
Oh, weird - I'm pretty sure I didn't change the email body at any point.

**Comment by jmduke** [comment]
Bizarre! Still, will poke around.
