### ISSUE TITLE
Add internal link re-writing

### ISSUE THREAD

**Issue by jmduke** [buttondown/roadmap#2441]
When folks import archives from another provider like Substack or Mailchimp, those archives will often have links to their old newsletter.  Imagine a Tinyletter archive with two emails:

- `https://tinyletter.com/jmduke/letters/1`
- `https://tinyletter.com/jmduke/letters/2`

https://tinyletter.com/jmduke/letters/2 might have a link to https://tinyletter.com/jmduke/letters/1; we want to break to rewrite that link to point to the _new_ permalink on Buttondown's side (https://buttondown.email/jmduke/archive/1 or whatever.)

In due time, we'd like to have this be part of the overall archive import process; for the purpose of this issue, though, it can just be something that can be run ad-hoc (so it can exist in `emails/models/email/actions`).

## Proposed steps

I haven't thought _super_ hard about how to do this, so there might be an easier way, but this is what I suggest:

- [ ] Create a field on the Email model, `Email.previous_canonical_url`. This represents, for imported emails,  the previous permalink (e.g. https://tinyletter.com/jmduke/letters/1). 
- [ ] Start populating that field within one or two archive imports! (The tinyletter archive import might be a good starting point, since it's pretty simple and there are some test data in Notion.) 
- [ ] Create an action that takes a given email and checks every link to see if any of them exist as a `previous_canonical_url`, and if they do — replace it with the email's `get_absolute_url`.

**Comment by tanvirraj** [comment]
@jmduke we can close this
