### ISSUE TITLE
Switching between Markdown and Rich Text changes quote formatting in Preview

### ISSUE THREAD

**Issue by efletch** [buttondown/roadmap#2489]
Rich text mode shows a break between the lines while Markdown shows a multiple line quote

<img width="1091" alt="Screen Shot 2024-02-26 at 12 51 45 PM" src="https://github.com/buttondown-email/roadmap/assets/3475400/238c8c44-3fd8-41e8-9494-bc5aa667a396">

<img width="1093" alt="Screen Shot 2024-02-26 at 12 51 55 PM" src="https://github.com/buttondown-email/roadmap/assets/3475400/dce30103-3e86-4b15-b885-0e1e6a915430">

https://secure.helpscout.net/conversation/2521356916/3320

**Comment by tk04** [comment]
@jmduke I'm assuming that a break between the lines is the expected behavior. In this case, would it be better to save the email body only in HTML format (and convert that based on the editor mode)? Or should we do some preprocessing to add spacing between adjacent quotes?

**Comment by jmduke** [comment]
Great question. I think philosophically, the answer is the former — Markdown is just kind of a crappy message bus, and this is a symptom of that. For the purposes of this specific issue, I think we can just do the latter and pre-process the markdown to enforce that space.
