### ISSUE TITLE
Subscribe Button Not Reflecting Chosen Color when in Email Editor

### ISSUE THREAD

**Issue by dlwoda** [buttondown/roadmap#2515]
https://secure.helpscout.net/conversation/2530043661/3460/

User reported the Subscribe button displaying as default color as opposed to the selected tint in the settings.  Upon investigation, the button does display as blue in email editor view, but when selected, does display as the customized tint color.

![image](https://github.com/buttondown/roadmap/assets/161613019/c679874d-d72a-4889-a142-a3675fe59c04)

![image](https://github.com/buttondown/roadmap/assets/161613019/67913a26-b5ff-4418-b930-6c0491b843dd)

**Comment by dlwoda** [comment]
Users reporting this behavior again on the Modern template. Subscribe button at top of page is correct, but the lower button is default blue
![image](https://github.com/buttondown/roadmap/assets/161613019/808bb2a5-2ea0-4d9f-93d3-6ee8da97abb9)
![image](https://github.com/buttondown/roadmap/assets/161613019/c0746637-e804-4cdc-8bb3-0b428ad9a08d)

https://secure.helpscout.net/conversation/2530965064/3474?folderId=8083960

**Comment by dlwoda** [comment]
Users who were using Classic, switched to Modern, and then back to Classic are also experiencing the Subscribe button not reflected selected tint
https://secure.helpscout.net/conversation/2530043661/3460/

**Comment by jmduke** [comment]
(Re-opening!)

**Comment by benborgers** [comment]
Related thing (but can file separately if you'd like @jmduke) — the links in the newsletter description aren't tinted with the tint color either:

<img src=https://github.com/buttondown/roadmap/assets/30215449/754402d5-6141-4143-823a-8b860cb61978 height=400 />

**Comment by dmoklaf** [comment]
Any news on this one? The pages are so simple this stands out and doesn't look good.

**Comment by jmduke** [comment]
Fixed!

**Comment by dmoklaf** [comment]
Great ! One thousand thanks
