### ISSUE TITLE
RSS feed has spurious whitespace before the content

### ISSUE THREAD

**Issue by clorgie** [buttondown/roadmap#2516]
Below is an example of an item in my RSS feed. Note the four spaces before the content (line 2). This causes issues because when I display the feed in another system, the initial spaces are interpreted as Markdown and the line becomes block quote. Can you prevent the system from introducing whitespace there? Thanks!

```rss
<item><title>00322 ◊ Rain ◊ Jack Gilbert</title><link>https://dailyish-poem.wyrdbyword.xyz/archive/00322-rain-jack-gilbert/</link><description>
    &lt;p&gt;&lt;strong&gt;Rain&lt;/strong&gt;&lt;/p&gt;
&lt;p&gt;Suddenly this defeat.&lt;br /&gt;
This rain.&lt;br /&gt;
The blues gone gray&lt;br /&gt;
and yellow&lt;br /&gt;
a terrible amber.&lt;br /&gt;
In the cold streets&lt;br /&gt;
your warm body.&lt;br /&gt;
In whatever room&lt;br /&gt;
your warm body.&lt;br /&gt;
Among all the people&lt;br /&gt;
your absence.&lt;br /&gt;
The people who are always&lt;br /&gt;
not you.&lt;/p&gt;
&lt;p&gt;I have been easy with trees&lt;br /&gt;
too long.&lt;br /&gt;
Too familiar with mountains.&lt;br /&gt;
Joy has been a habit.&lt;br /&gt;
Now&lt;br /&gt;
suddenly&lt;br /&gt;
this rain.&lt;/p&gt;
&lt;p&gt;—&lt;a href="https://wyrdbyword.xyz/l/jack-gilbert" target="_blank"&gt;Jack Gilbert&lt;/a&gt;&lt;br /&gt;
—found in &lt;a href="https://wyrdbyword.xyz/l/jack-gilbert-views-jeopardy" target="_blank"&gt;&lt;em&gt;Views of Jeopardy&lt;/em&gt;&lt;/a&gt; (1962)&lt;/p&gt;

</description><pubDate>Tue, 05 Mar 2024 14:00:00 +0000</pubDate><guid>https://dailyish-poem.wyrdbyword.xyz/archive/00322-rain-jack-gilbert/</guid></item>
```

**Comment by jmduke** [comment]
@clorgie Was this for a draft of the RSS send, or an active automation? I'm not finding the relevant item in the database, and I suspect that the spaces might be because of the template itself.

**Comment by clorgie** [comment]
The example is taken directly from a Buttondown newsletter feed of sent items, in this case: https://dailyish-poem.wyrdbyword.xyz/rss

As you can see there, every item has this extra space appended at the beginning though it does not exist in the content.

**Comment by jmduke** [comment]
@clorgie Ohhhh I see — I should have had more coffee before I read this, you're talking about the feed we _generate_. Yeah, I can see how this is happening; can fix this week.

**Comment by jmduke** [comment]
@clorgie Fix going live right now!
