### ISSUE TITLE
[Vue warn]: Error in 1: "TypeError: Cannot convert undefined or null to object" at emails.ts:95

### ISSUE THREAD

**Issue by james-baker** [buttondown/roadmap#2526]
Repros for both emails I've sent today. Does not repro for week-old email.

Repro:
load https://buttondown.email/emails/
Open the 3-dot menu for the email I just sent.
Click "Analytics"

Expected: Analytics dialog
Actual: window gets grey glass, no dialog, error in console

https://buttondown.email/emails/analytics/26e43f5d-5a41-43b6-917a-764f0bc7950a

[Vue warn]: Error in 1: "TypeError: Cannot convert undefined or null to object"

**Comment by jmduke** [comment]
Aaand fixed! T/Y for reporting.
