### ISSUE TITLE
Utilizing & or ' when utilizing name metadata in Subject displays improperly

### ISSUE THREAD

**Issue by dlwoda** [buttondown/roadmap#2547]
https://secure.helpscout.net/conversation/2537336634/3566?folderId=7228476

User reported that when utilizing the & or ' characters in their name metadata, they do not display properly in the Subject line of email. 

![2024-03-14 at 07 25 18@2x](https://github.com/buttondown/roadmap/assets/30215449/1191852f-abe8-4e4f-b7aa-091da1ca381b)

**Comment by jmduke** [comment]
Gross, yup. Will get this fixed today.
