### ISSUE TITLE
Markdown coding on images lost when switching from markdown to rich text

### ISSUE THREAD

**Issue by dlwoda** [buttondown/roadmap#2548]
https://secure.helpscout.net/conversation/2530377657/3462/

User reported placing code to align image left while in Markdown mode, but it disappearing when changed back to rich text reverting the image back to default centered. The change to resize image "w" remains.
expected behavior is for the code to remain to allow the image alignment to be changed so the user can continue using rich text for writing email
![image](https://github.com/buttondown/roadmap/assets/161613019/261311cb-2cae-4712-a23c-506c0177944d)

**Comment by jmduke** [comment]
@mary-ext just throwing this at you as I suspect it might be the same thing as https://github.com/buttondown/roadmap/issues/3156

**Comment by mary-ext** [comment]
Hmmm I wonder if I can tack on additional/unknown properties to the image element, sounds like it got lost when Tiptap/ProseMirror converts the HTML into its own document representation

**Comment by mary-ext** [comment]
I don't believe we'd be able to do that sort of image positioning with the fancy mode though, at least not one that's doable by just preserving the image attributes

sooo... should we keep these extra HTML attributes even if they'll introduce discrepancies between the WYSIWYG editor and the email/preview? @jmduke

**Comment by jmduke** [comment]
Blech. My instinct is to say no, and instead do what we quasi-do with Naked mode now which is just warn people before switching. How feasible is it to be able to _detect_ the extra HTML attributes just so we can throw up a dialog in cases like this? (I don't think it needs to be a perfect/rigorous detection process, just catch the 80% of things like this.)

**Comment by mary-ext** [comment]
Hmmm I suppose we could do it as part of Markdown to HTML conversion, will have to look into it

**Comment by mary-ext** [comment]
This is made complicated by how we're dealing with mode transitions I think, mode changes are handled by the page itself but the actual body conversion is dealt by our editor.

Ideally if we were to show a modal that warns about this it would've been done before the editor and mode gets swapped for another
