### ISSUE TITLE
New settings pages don't update when switching between newsletters

### ISSUE THREAD

**Issue by james-baker** [buttondown/roadmap#2549]
Be on a settings page like https://buttondown.email/settings/subscribing
Switch newsletters using the top-left switcher

Expected: Everything updates, I'm looking at the settings of the selected newsletter
Actual: The screen keeps all the settings of the previous newsletter, and puts up the "You've got some unsaved changes." banner.

That could be VERY bad for folks trained to click "Save changes" - would overwrite the settings of one newsletter with the other.

**Comment by jmduke** [comment]
🙏 Fix going live rn!

**Comment by james-baker** [comment]
Fix verified!
