### ISSUE TITLE
Disabling "Enable paid subscriptions?" does not persist after Save

### ISSUE THREAD

**Issue by efletch** [buttondown/roadmap#2552]
https://secure.helpscout.net/conversation/2540274833/3605

Steps to reproduce
* Have an account with Enable Paid Subscriptions? turned on
* Toggle "Enable Paid Subscriptions?" off
* Click Save change in bottom toolbar
* Green Updated Settings message shows and "Enable Paid Subscriptions?" appears off
* Refresh the page
* "Enable Paid Subscriptions?" shows as on

**Comment by jmduke** [comment]
Closing as dupe of https://github.com/buttondown/roadmap/issues/2400.
