### ISSUE TITLE
Subscribe Button not rendering tint on drafts/emails

### ISSUE THREAD

**Issue by dlwoda** [buttondown/roadmap#2556]
https://secure.helpscout.net/conversation/2542445451/3635?folderId=7228476
https://secure.helpscout.net/conversation/2544223890/3665/
User reported the Subscribe button not displaying on draft email. Tested and the button is there and responsive, but not rendering tint color for button.  You can see the Subscribe white text if you have dark view on your browser.

![image](https://github.com/buttondown/roadmap/assets/161613019/4d6e24d3-eaa8-4c71-8a82-c08a11866080)

![Screenshot_20240318_103625_Gmail](https://github.com/buttondown/roadmap/assets/161613019/39c4c096-a66b-44ef-85a6-6f435780195d)

**Comment by dlwoda** [comment]
new reported occurrence  https://secure.helpscout.net/conversation/2568654551/3921?folderId=8083960
The buttons are rendering on archive, but not in email.  If you hover over the area where button "is", you can click on link to navigate to link page

**Comment by jmduke** [comment]
@dlwoda Fix rolling live now!
