### ISSUE TITLE
Unable to add Team members 

### ISSUE THREAD

**Issue by dlwoda** [buttondown/roadmap#2561]
https://secure.helpscout.net/conversation/2543563032/3658/

User reported that upon clicking on Invite, window closes immediately upon selecting a field to type. Unable to invite colleagues to Team. Confirmed behavior.

**Comment by parksmithh** [comment]
hey @jmduke I'm still encountering the issue, can you confirm when the fix is live?

**Comment by jmduke** [comment]
@parksmithh Mind trying now? (You may need to force-refresh to pull in the new CSS bundle.)
