### ISSUE TITLE
Duplicate subscribe bars at bottom of premium articles, when not logged in

### ISSUE THREAD

**Issue by ifpingram** [buttondown/roadmap#2564]
Seeing the following on:

https://news.france-insider.com/archive/the-most-beautiful-villages-of-france?utm_source=ifp

<img width="936" alt="Screenshot 2024-03-20 at 08 14 31" src="https://github.com/buttondown/roadmap/assets/1426859/4c7ce1a4-a46b-4969-a532-4693cd56de78">

**Comment by jmduke** [comment]
Fix going live!
