### ISSUE TITLE
Migrate off of `hotkeys.js`

### ISSUE THREAD

**Issue by james-baker** [buttondown/roadmap#2594]
Repro:
Just load up the app on any regular page and look at the left nav sidebar.
Expected: Correct OS-specific keys/icon on any OS-specific displayed keyboard shortcuts
Actual: Command-button (MacOS-only) icon 
![image](https://github.com/buttondown/roadmap/assets/89615/10103cf2-55a1-45d3-9ff1-9874490a240a)

And if there's supposed to be a "K"-related shortcut, I can't find it on Windows.

I didn't see this mentioned in #1169 but maybe it's related.

**Comment by james-baker** [comment]
Also the "Preview" button in the markdown editor.

**Comment by jmduke** [comment]
After spiking on this a little bit, I think we must/should migrate off of https://github.com/jaywcjlove/hotkeys-js since it's handling plexing between the two oddly. (Also our use case is just not quite large enough to warrant pulling this in.)
