### ISSUE TITLE
Subscribers list not loading today

### ISSUE THREAD

**Issue by james-baker** [buttondown/roadmap#2609]
![image](https://github.com/buttondown/roadmap/assets/89615/9eb06d47-7f7d-4b99-af32-4aa8677baaa1)

https://buttondown.email/subscribers?order=-date
(via SPA-click, URL hard load, Ctrl-F5, any way I can hit it)

I think the data loads for a flash, a fraction of a second before it disappears again and the page gets stuck in an infinite loop loading 3 requests over and over.

Chrome on Windows.

Edit: If I click the "Add" (new subscriber) button, something about that can sometimes get the list to display behind the modal? But it still has the "Loading" thing going even then...

**Comment by jmduke** [comment]
Sanity check: no extensions, right? (Trying and failing to repro this ATM.)

**Comment by james-baker** [comment]
(Extensions: just built-in default "Google Docs Offline" as the only one)
Coming back to this the next day (and switching newsletters back and forth a bit):
Subscriber list seems to be loading reliably now.

There's still an infinite loop of requests constantly streaming while the page is doing nothing. Just two today: "utm_source" and "subscriber_type" keep looping, about once every second each. Yesterday "tags" was in there as a 3rd request on infinite loop. 1000 requests while I've been typing this, this must be 10Xing your backend load even if these are lightweight requests.

The console has a bunch of errors (like usual... why is this so common?)
GETs for https://buttondown.email/v1/coupons?page=1 and https://buttondown.email/v1/prices?page=1 are 400s, with "Uncaught (in promise) error" seemingly still re-throwing those (all?) errors.
A bunch of load failures /api/emails/aggregate/subscriber/tags:1 that are marked "Failed to load resource: net::ERR_NETWORK_IO_SUSPENDED"

But yeah nothing that's as bad as "whole list disappears, infinite spinner".

**Comment by james-baker** [comment]
No repro again today.
Maybe this is the same caching stuff as #2094?
