### ISSUE TITLE
`Dropdown` is broken when used in conjunction with container queries

### ISSUE THREAD

**Issue by jmduke** [buttondown/roadmap#2630]
Sadly, this will require migrating from Popper to `floating-ui` (https://github.com/floating-ui/floating-ui/pull/2402/files).

See https://share.cleanshot.com/Cxc5Pqw8, though I just hid the relevant buttons for now.

**Comment by jmduke** [comment]
@benborgers Are you still able to repro this if you unhide those comments whilst the preview is open? I am not.

**Comment by benborgers** [comment]
@jmduke Can't reproduce this bug anymore! Shall I close?
