### ISSUE TITLE
sample badge for markdown 

### ISSUE THREAD

**Issue by epogrebnyak** [buttondown/roadmap#2636]
I would line to link a buttondown mailint list from a README on githb, came up with a trivial badge like this, where `mlmw` is the newsletter name:

![subscribe](https://img.shields.io/badge/buttondown-mlmw-blue)

```
![subscribe](https://img.shields.io/badge/buttondown-mlmw-blue)
```

Would appreciate any guidance on colors or logo to make the badge more aligned with the buttondown brand. 

Thanks for providing and developping the service, my mailing list is just 5 subscribers as of now, but I enjoy maintaining it.

**Comment by jmduke** [comment]
Thanks for the kind words :)

Only tweak I'd suggest is to use our brand hex, 0069ff:

https://img.shields.io/badge/buttondown-mlmw-0069ff
