### ISSUE TITLE
Unsaved settings widget can cut off stuff in the settings page

### ISSUE THREAD

**Issue by jmduke** [buttondown/roadmap#2654]
Simplest possible example:

![image](https://github.com/buttondown/roadmap/assets/461046/91c6d1d3-e59f-4902-ad8d-c8ace8544aeb)

We should/can just add a bottom padding to all the relevant pages that use this widget.

**Comment by mary-ext** [comment]
@jmduke Haven't looked at this deeply yet but I can see three approaches that we can go for this:

1. Set `position: sticky` on the widget such that it leaves permanent mark on the page, no need to mess around with padding
2. If all pages shares a class/ID that we can target, then have a global CSS selector that adds additional padding to the bottom of the page, but only if the widget is shown (`:has()` selector)
3. Manually change the paddings on each page that has this widget (the suggested option)
