### ISSUE TITLE
Customize top-line CTAs for marketing site when on certain pages

### ISSUE THREAD

**Issue by jmduke** [buttondown/roadmap#2669]
For example: _if_ on a comparison page, change the CTA from "Build your newsletter" to "Migrate in minutes"

**Comment by smonette** [comment]
Justin beat me to it! This went in last week in this commit: https://github.com/buttondown/monorepo/commit/b6558a8c4cd7742bed3c3df7b85439d12913c910

I'll fix the failing Biome test here: https://github.com/buttondown/monorepo/pull/1450
