### ISSUE TITLE
Add the ability to pause surveys

### ISSUE THREAD

**Issue by jmduke** [buttondown/roadmap#2692]
More state / options for surveys :)

Sometimes authors want to pause their surveys. Let's first work on the backend support for this:

1. All surveys are default "active".
2. Add a state, `Survey.status`, that has two values (`active`, `inactive`)
3. Add a bulk action to the dashboard so that authors can toggle whether or not the survey is active
4. Add logic to `answer` to check to see if the survey is active before recording the response

**Comment by tanvirraj** [comment]
not finished yet bro @jmduke 😄

**Comment by jmduke** [comment]
I closed the wrong one 🤦

**Comment by tanvirraj** [comment]
@jmduke , we can close it now
