### ISSUE TITLE
Add ld/json to subscribe pages

### ISSUE THREAD

**Issue by jmduke** [buttondown/roadmap#2711]

**Comment by catdevnull** [comment]
Any previous art? I also can't seem to find a type/schema to use. Maybe https://schema.org/SubscribeAction?

**Comment by jmduke** [comment]
ah doi. How about just `WebSite`? It can be fairly generic, but also that's a super-rich type so there's a lot to populate.

**Comment by catdevnull** [comment]
I'm not sure what to populate or not as I don't really have a target. Google doesn't seem to care about `WebSite`. Would this be enough?

```html

    <script type="application/ld+json">
    {
        "@context": "https://schema.org",
        "@type": "WebSite",
        "url": "{{ newsletter.get_absolute_url }}",
        "name": "{{ newsletter.name }}",
        "description": "{{ newsletter.description }}",
        {% if newsletter.icon %}
        "image": {
            "@type": "ImageObject",
            "contentUrl": "{{ newsletter.icon }}",
            "thumbnailUrl": "{{ newsletter.icon }}"
        },
        {% endif %}
        "publisher": {
            "@type": "Organization",
            "name": "{{ newsletter.name }}",
            "url": "{{ newsletter.get_absolute_url }}",
            "description": "{{ newsletter.description }}",
            {% if newsletter.icon %}
                "identifier": "{{ newsletter.id }}",
                "image": {
                    "@type": "ImageObject",
                    "contentUrl": "{{ newsletter.icon }}",
                    "thumbnailUrl": "{{ newsletter.icon }}"
                }
            {% else %}
                "identifier": "{{ newsletter.id }}"
            {% endif %}
        }
    }
    </script>
```

**Comment by jmduke** [comment]
That looks good, with a couple additions:

- `mainEntityOfPage`
- `sameAs`, populated with any social network links that the newsletter has
- `identifier` (can be the UUID)

**Comment by catdevnull** [comment]
>mainEntityOfPage

What's supposed to be the value of this? 

>sameAs, populated with any social network links that the newsletter has

Ugh, `newsletter.social_networks` isn't directly an array of URLs, but rather something like `{ twitter: 'esoesnulo', github: 'catdevnull' }`. I can't find a helper function that converts these to URLs, only `app/emails/templates/subscriber_facing/snippets/social.html` which converts it into HTML anchors. 

Should we wait until #3308 to add those instead?
