### ISSUE TITLE
Provide a way to see which email a survey response was submitted on

### ISSUE THREAD

**Issue by efletch** [buttondown/roadmap#2755]
This notification provides some context but not the email it was submitted on

![image](https://github.com/buttondown/roadmap/assets/3475400/6cb1d1fe-ca6a-4b60-b541-3eb94b23e451)

Another option is to include in Listing survey responses API

([Link to HS Ticket](https://secure.helpscout.net/conversation/2600807937/4333))

**Comment by tanvirraj** [comment]
@jmduke , we can close it now

**Comment by jmduke** [comment]
@tanvirraj Feel free to close these yourself if/when you've finished them!
