### ISSUE TITLE
The editor toolbar is hidden on long emails (Firefox)

### ISSUE THREAD

**Issue by efletch** [buttondown/roadmap#2758]
When scrolling through an email, the editing toolbar scrolls up and out of frame, making it impossible to use when editing an email longer than one "screenful." There is a faint grey horizontal line that scrolls up from the bottom of the screen (it's initially hidden behind the bottom toolbar). When this line meets the editing toolbar, the toolbar scrolls up out of sight.

OS: Mac OSX Monterey
Browser: Firefox 126.0

Repro steps:

1) start a new email
2) add text to create an email that stretches "below the fold" (i.e. extends below the editing pane), at least twice the height of the editing pane.
3) note the position of the editing toolbar at the top of the pane
4) scroll down to the bottom of the email

Expected:
The editing toolbar remains visible throughout

Actual/Observed:
The editing toolbar scrolls up out of frame at the midpoint of the scroll length, becoming inaccessible.

([Link to HelpScout](https://secure.helpscout.net/conversation/2601465656/4344))

**Comment by dlwoda** [comment]
[Link to HelpScout ](https://secure.helpscout.net/conversation/2613125198/4496/)
User included video of editor experience and the toolbar disappearing on editor scrolling

**Comment by dlwoda** [comment]
[Link to HelpScout](https://secure.helpscout.net/conversation/2614770897/4524?folderId=8083960)

User reported the toolbar disappears when scrolling down in editor

**Comment by dlwoda** [comment]
[Link to HelpScout](https://secure.helpscout.net/conversation/2617437204/4558?folderId=7228473)

User reported "toolbar disappearing in compose mode". Included experience images

**Comment by dlwoda** [comment]
[Link to HelpScout](https://secure.helpscout.net/conversation/2618307579/4567?folderId=7228473)
when I scroll down to the latest part of the draft I'm working on, the formatting bar disappears. I can still type the draft, but I can't do any formatting on it.
