### ISSUE TITLE
docs: Standardize data for examples

### ISSUE THREAD

**Issue by smonette** [buttondown/roadmap#2806]
Currently, our examples are spanning a lot of different fandoms (The Simpsons, Pokemon, 30 Rock)  

These are all fantastic, but for ease of maintenance lets standardize examples.

**Comment by jmduke** [comment]
We officially do this with the fixture generation pipeline. While I don't think we should keep this open for a full-on rewrite of every bit of test data, I will force people who are adding new test data to make sure to use the pipeline!

**Comment by smonette** [comment]
Yay that's fantastic! I'll go ahead and close this out
