### ISSUE TITLE
Replace janky code generation pipeline with `httpsnippet`

### ISSUE THREAD

**Issue by jmduke** [buttondown/roadmap#2818]

**Comment by catdevnull** [comment]
Hmmm...

It seems that @readmeio has their own [httpsnippet fork](https://github.com/readmeio/httpsnippet) that is seemingly more maintained and works directly with their [oas library](https://github.com/readmeio/oas/tree/7f44fe975c7f3a28955b558d0a8e96fd6784b7ff/packages/oas-to-snippet)

I'm going to try and use the `oas` packages directly, although I am stumbling upon some issues (for example, it doesn't seem to automatically detect examples for the body of a request from the schema)

**Comment by jmduke** [comment]
sgtm. Broadly speaking, I don't feel super strongly about the specific packages or frameworks we go with so long as the final inputs and outputs are what we want
