### ISSUE TITLE
Small typo on Buttondown vs. Minutemailer page

### ISSUE THREAD

**Issue by efletch** [buttondown/roadmap#2854]
https://buttondown.email/comparisons/minutemailer

- "Buttondown offers three main things that Buttondown does not" --> Should probably be "Buttondown offers three main things that Minutemailer does not"
- "Buttondown offers the crucial features that MailerLite lacks" --> "Buttondown offers the crucial features that Minutemailer lacks"
- Mixed use of **Minutemailer** (little second m) and **MinuteMailer** (big second m)

**Comment by smonette** [comment]
Hey Emma! Thanks for flagging these typos. The fixes have been made ✅
