### ISSUE TITLE
Survey notifications still fire when turned off

### ISSUE THREAD

**Issue by benborgers** [buttondown/roadmap#2855]
Even though notifications for "Survey responses" are turned off in Settings > Notifications, I still get an email when someone clicks a response for a survey.

**Comment by jmduke** [comment]
@benborgers Do you have a specific email we can reference for this?

**Comment by benborgers** [comment]
@jmduke I repro'd it on my `ben-admin` account this morning, here's the email I got: https://account.postmarkapp.com/servers/4717932/streams/outbound/messages/42baa39a-38de-43d2-88a1-ae9a390e16e1
