### ISSUE TITLE
When selecting a very long piece of text that is greater than the viewport, we should have the editor popup be in frame

### ISSUE THREAD

**Issue by jmduke** [buttondown/roadmap#2875]

**Comment by mary-ext** [comment]
Still digging into Tippy's configuration, not sure why `preventOverflow` isn't working. Given that Tippy is essentially a wrapper for Popper.js it might be the same issue as https://github.com/buttondown/roadmap/issues/2630?

**Comment by mary-ext** [comment]
Doesn't seem to be an issue with container queries, I've probed around Tippy settings and removing `@container` from the layout, doesn't seem to make a dent.

I've dug around the code and it seems like it's heavily wired around Tippy.js' API, which makes it hard to replace with Floating UI. Will have to look for another way.
