### ISSUE TITLE
Email Replies losing formatting - line breaks disappear

### ISSUE THREAD

**Issue by dlwoda** [buttondown/roadmap#2903]
[Link to HelpScout](https://secure.helpscout.net/conversation/2627121640/4636)

When I get notifications from Buttondown about replies, the formatting is strange.

Line breaks disappear, and what seems to be someone's signature gets formatted weirdly.

The content is bunched together

**Comment by jmduke** [comment]
Closing in favor of https://github.com/buttondown/roadmap/issues/2162.
