### ISSUE TITLE
Options menu for Subscriber on results page requires scroll to view

### ISSUE THREAD

**Issue by dlwoda** [buttondown/roadmap#2933]
[Link to HelpScout](https://secure.helpscout.net/conversation/2632305148/4711/) - video on HS

Author reported that on the search results page, the options dropdown accessed from the ellipses ... does not fully show list.  Requires you to scroll to select an option

![image](https://github.com/buttondown/roadmap/assets/161613019/43bc27e8-b660-438a-ae08-e62631462ca5)

**Comment by mtlynch** [comment]
Fix confirmed, thanks!
