### ISSUE TITLE
Comments off by default -- or are they?

### ISSUE THREAD

**Issue by krangor** [buttondown/roadmap#2936]
I have comments turned on for both my newsletters; however, in the web archive sidebar when editing an issue (sent or not), I always see this:

<img width="348" alt="image" src="https://github.com/buttondown/roadmap/assets/165304828/c7cc2ab5-2621-4fde-aba3-6739d2d82e44">

...with the switch set to OFF by default.

This leads me to worry about remembering to check the box before I sent an email. BUT...

Checking back, archived issues have the box checked OFF but indeed have a comment box on the archive page. So can I safely ignore this?

**Comment by jmduke** [comment]
That's a terrible label/toggle. Your understanding is correct — that toggle basically represents "are comments disabled?" I will flip it and improve the description.

**Comment by jmduke** [comment]
:sob:

**Comment by jmduke** [comment]
Here's the new default:

![image](https://github.com/buttondown/roadmap/assets/461046/a8778d9d-96de-4044-8e04-7bcd5e18eb6f)

**Comment by krangor** [comment]
Much better. BTW, the ones I had turned off still seem to have a comment box at the bottom?
