### ISSUE TITLE
Mobile rich text editor needs more bottom padding on mobile

### ISSUE THREAD

**Issue by benborgers** [buttondown/roadmap#2942]
See video in thread: https://secure.helpscout.net/conversation/2631262652/4688

**Comment by jmduke** [comment]
@benborgers did we fix this?

**Comment by benborgers** [comment]
I don't think so (peep the top of the text at the bottom). 

<img src=https://github.com/user-attachments/assets/38ebe414-8b2d-40c7-9f11-a6fdb4473d02 height=700 />
