### ISSUE TITLE
Preserve HTML comments when switching between markdown/rich text

### ISSUE THREAD

**Issue by benborgers** [buttondown/roadmap#2976]
Brought up in Discord: https://discord.com/channels/1044735046919127160/1073231552516993086/1256428593546924052

**Comment by mary-ext** [comment]
Hmmmm, pretty sure we can't import HTML comment nodes as a Tiptap/PM node so I think we'll have to introduce a special paragraph `<p class=buttondown-comment>` that gets stripped out by the email renderer.

`<!-- hello world -->` gets converted into `<p class=buttondown-comment>hello world</p>` and vice versa by the client-side conversion.

WDYT? @jmduke

**Comment by jmduke** [comment]
I don't mind that approach, but can we just go even cruder and do a validation — if we detect any comments, just alert them before we commit to the switch to rich (similar to how we do for naked?)
