### ISSUE TITLE
Add support for nested dropdowns

### ISSUE THREAD

**Issue by jmduke** [buttondown/roadmap#2983]
This sort of thing:

![image](https://github.com/buttondown/roadmap/assets/461046/a95918d1-a581-46c4-9574-d047a7db515e)

**Comment by jmduke** [comment]
No strong feeling on the API here — I trust your judgment.

**Comment by mary-ext** [comment]
Quick look seems to suggest that Headless UI doesn't support this kind of thing.

Given that we have Radix Vue for the resizable panels already, might look towards moving dropdown menus there.
