### ISSUE TITLE
Stripe tax collection not collecting from Upgrade button

### ISSUE THREAD

**Issue by dlwoda** [buttondown/roadmap#2988]
[Link to HelpsScout](https://secure.helpscout.net/conversation/2640205297/4777?folderId=7228473)

User reported that when a subscriber clicks on the upgrade button, they are not seeing the tax being collected.  If the payment link is used instead of the button, the tax is collected.
![image](https://github.com/buttondown/roadmap/assets/161613019/2ff72572-0716-45ed-a8e8-e224250126e2)
![image](https://github.com/buttondown/roadmap/assets/161613019/ad92937f-9764-4aca-81f5-095682ef3418)

**Comment by carltongibson** [comment]
Thanks @dlwoda 👍 

@jmduke Can I be a pain and express the need for this to work. If you're EU based (particularly I think) collecting tax is in no-way optional at all, and so this not working is a bit of deal breaker. I've just had a nasty shock and a lot of backfilling when preparing the quarterly returns 😬

I see you've labelled it already. Thanks.

**Comment by carltongibson** [comment]
Not sure is this detail came across from the report: 

> Looking at the Stripe logs .. when opening from Buttondown the
`automatic_tax.enabled` boolean is not provided and this is causing the problem:
>  
> https://docs.stripe.com/api/checkout/sessions/create#create_checkout_session-automatic_tax
>  
> From the response:
>
> ```json  
>  "automatic_tax": {
>     "enabled": false,
> ```
 > 
> That needs to be set to true (via the request) to enable tax collection.

**Comment by jmduke** [comment]
Done!

**Comment by carltongibson** [comment]
Awesome. Thanks for resolving that @jmduke 🎁

**Comment by carltongibson** [comment]
@jmduke — I don't know if you'll see this... 😬 

There's one more bit to make it equivalent to the payment link version which is to set the tax id collection parameter. 

https://docs.stripe.com/api/checkout/sessions/create#create_checkout_session-tax_id_collection


Without (Current upgrade button): 

![Screenshot 2024-07-09 at 09 07 24](https://github.com/buttondown/roadmap/assets/64686/e8c110c9-95ca-4254-af1f-80111ebc5cea)


With (payment link): 

![Screenshot 2024-07-09 at 09 07 39](https://github.com/buttondown/roadmap/assets/64686/c9886475-09aa-423a-babb-e71833a2a45b)


This isn't as urgent at all, but a good to have too.

**Comment by jmduke** [comment]
I _did_ see it (if not immediately!) Will get this sorted.

**Comment by carltongibson** [comment]
Looking good. Thanks again for resolving this @jmduke 🎁
