### ISSUE TITLE
Multiple "cmd+I to copy" commands fire at once

### ISSUE THREAD

**Issue by benborgers** [buttondown/roadmap#3009]
When I hit cmd+I on a subscriber page, everything copies at once. Ideally only the hovered one (?) should trigger. 

![2024-07-04 at 09 44 11@2x](https://github.com/buttondown/roadmap/assets/30215449/b11f7c7b-6d7e-4b52-b12a-d9c6ccfec18e)

**Comment by mary-ext** [comment]
I'm guessing this is Mac-specific because that Copy shortcut doesn't seem to work for me and when looking at it, it appears that we're binding `cmd+i` on mount and unbinding `ctrl+i` on unmount

**Comment by mary-ext** [comment]
Aha, this seems to be stemming from the fact that we also have 3 copiable component instances in the subscriber details drawer. I'm going to prioritize the email first over anything else.
