### ISSUE TITLE
inconsistent UI state after "send archived email"

### ISSUE THREAD

**Issue by james-baker** [buttondown/roadmap#3021]
Repro:
Go to subscribers page
Select first subscriber in the list (a just-added new person)
Click "Send archived email", select email from dialog, done, sent.
After the dialog goes away,
The UI then refreshes itself in this way:
![image](https://github.com/buttondown/roadmap/assets/89615/115f832c-e86a-4401-a28b-3f9aaf3b0a88)

Expected: selection is kept in both the per-row checkboxes and the selection summary at bottom
Actual: selection is lost in the per-row checkboxes, but still exists in the backing data and summary

In this state, I clicked that first checkbox again (because I wanted to send them another archived email). When I did that, the bottom bar decided that I was UNSELECTING it, so when that first checkbox looked selected, the bottom bar said 0 selected and didn't let me do anything.

Seems like there's invisible checkbox state that wasn't affected by the UI refresh of the list.

**Comment by jmduke** [comment]
Have a fix for this that requires some Typescript shenanigans. Should get it live tomorrow.
