### ISSUE TITLE
Drafts coming in gnarly, unformatted, subscribe button invisible, text too small, etc on Gmail

### ISSUE THREAD

**Issue by krangor** [buttondown/roadmap#3024]
Hi! I'm testing my latest email and it's coming in VERY weird on Gmail (though not on Apple Mail for macOS or iOS). I'm a little worried to send out the actual email in the meantime, unless you can assure me it's just a "draft thing" (it actually looks like previews used to look in the editor, if that makes any sense).
![image](https://github.com/buttondown/roadmap/assets/165304828/50c98f89-3740-4270-9286-e88a88da02f3)
![image](https://github.com/buttondown/roadmap/assets/165304828/1f08f10f-5838-40cf-bc6f-44fbe4887bd8)
Screenshots attached!

**Comment by jmduke** [comment]
Taking a look right now.

**Comment by jmduke** [comment]
@krangor Any chance you just changed some of your CSS? I tried fixing a couple missing semi-colons and then sent my self a draft and we appear to be back in business.

**Comment by krangor** [comment]
I don't recall doing that but it's entirely possible I messed something up in there. Thanks for the speedy response.
