### ISSUE TITLE
Unship `tippy.js`

### ISSUE THREAD

**Issue by jmduke** [buttondown/roadmap#3030]
We only use it now in the autocomplete menu (having chosen it b/c that's what we were using in tiptap's BubbleMenu, which we've since forked to use `floating-ui` instead), and it seems like it should be painless to rip that one out!

**Comment by mary-ext** [comment]
I've dealt with Tiptap's suggestion plugin before and it's a whole mess, so this might take a bit. Going to clean up the three autocompletion menus we have so it's easier to work on I suppose
