### ISSUE TITLE
Churn off of FontAwesome and onto Heroicons

### ISSUE THREAD

**Issue by jmduke** [buttondown/roadmap#3034]
(This is going to be a bore, and a slog, and something that I imagine is somewhat hard to piecemeal, so feel free to punt on this for as long as you'd like)

I am sick of the FontAwesome icon set, I don't like the component API, I think their icons are kind of dated-looking now, let's just replace them en masse with https://heroicons.com/. I imagine the vast majority of the replacement should be pretty trivial 1:1 ones; feel free to ping me if there aren't any obvious mappings. (I am totally okay with sequencing this such that it's a gradual transition where that's possible, to defray the pain a bit)

**Comment by mary-ext** [comment]
currently looking into [vite-plugin-magical-svg](https://github.com/cyyynthia/vite-plugin-magical-svg) which should take care of the pitfalls around shipping our own set of icons (or Heroicons' that is)
