### ISSUE TITLE
Sniper Link button does not match on Modern archives

### ISSUE THREAD

**Issue by benborgers** [buttondown/roadmap#3036]
![2024-07-09 at 23 37 05@2x](https://github.com/buttondown/roadmap/assets/30215449/3b032dcd-2c21-4ac4-ac46-ede7a9b35314)

**Comment by jmduke** [comment]
While we're here, this is pretty gross:

![image](https://github.com/user-attachments/assets/21ee14e3-1b8b-4b9f-81f7-0bb32504a267)

**Comment by benborgers** [comment]
@jmduke Just going through my task backlog -- gross because of the big circle-y button, or something else? (What's your ideal end design?)

**Comment by jmduke** [comment]
@benborgers Gross b/c of wrapping, yeah. I think just consistency on height + border radius is sufficient.
