### ISSUE TITLE
Bubble menu is a little _too_ sticky

### ISSUE THREAD

**Issue by jmduke** [buttondown/roadmap#3041]
Throwing this your way @mary-ext as I think it's technically a bug with the bespoke BubbleMenu implementation: if you select an arbitrary string in the editor and then click to a non-document part of the browser (e.g. the sidebar), the editor correct loses focus but the bubble menu sticks around. I'm 90% sure this didn't happen in the original implementation (and if it did, we should still fix since it seems atypical)

**Comment by mary-ext** [comment]
Considered not problematic for now
