### ISSUE TITLE
Automatically create a PR for new branches

### ISSUE THREAD

**Issue by jmduke** [buttondown/roadmap#3050]

**Comment by jmduke** [comment]
@catdevnull One more (I think the last?!) CI thing for you while you've got it top of mind :)

_Assuming this is not crazy difficult_, let's set up an action such that if a new branch is pushed in the format of:

`roadmap-<id>`

GH automatically spins up a PR and adds a reference to the given roadmap item in that branch. Very simple (I think we can use https://github.com/peter-evans/create-pull-request/tree/main?), just saves us five seconds per PR.

**Comment by catdevnull** [comment]
Hmm, that create-pull-request seems more useful for other usecases as it actually creates a commit for changes..

I think it would make sense to try and write a script using https://github.com/actions/github-script, as it would also involve lightly parsing the branch name. Does that sound about right?

**Comment by jmduke** [comment]
Yes, agreed.
