### ISSUE TITLE
API breaking change - external_url -> absolute_url

### ISSUE THREAD

**Issue by ifpingram** [buttondown/roadmap#3054]
Hi

FYI, it seems that you have changed your API so that external_url is now absolute_url, whilst no longer supporting the previous key. It's broken our article import. Not a biggy, but probably best to support old keys / notify us of such changes.

Thanks!

**Comment by jmduke** [comment]
Ah, we did but should probably blast it more loudly:

https://docs.buttondown.email/api-changelog-2024-07-13

Were you writing to it, OOC? I thought I emailed everyone who had interacted with the field but must have mishandled the query.

**Comment by ifpingram** [comment]
Thanks Justin. Was unaware of this changelog. Will check this out first next time if things go wrong.

FYI we only read from the API, no writing to it, hence why we probably didn't come onto your list.

**Comment by jmduke** [comment]
Ahhh, that tracks.
