### ISSUE TITLE
Omnibus: Zapier triggers and actions

### ISSUE THREAD

**Issue by jmduke** [buttondown/roadmap#3068]
```[tasklist]
### Tasks
- [x] Trigger: subscriber tag addition/removal
- [x] Action: subscriber update
```

**Comment by jmduke** [comment]
(@catdevnull check DMs for a Loom on this one)

**Comment by catdevnull** [comment]
Should `Trigger: subscriber tag addition/removal` trigger upon a specific tag specified by the user? Or what's the use case? @jmduke
