### ISSUE TITLE
Fix outdated Webflow instructions

### ISSUE THREAD

**Issue by benborgers** [buttondown/roadmap#3076]
This page https://buttondown.email/blog/2019-10-11-adding-a-buttondown-subscription-form-to-webflow has outdated instructions for Webflow. 

Either: 

- Update the blog post retroactively. 
- Create a page on docs.buttondown.email for Webflow and add a banner to that blog post marking it as outdated and giving a link to the new doc. 

See this thread for a screenshot to use: https://secure.helpscout.net/conversation/2657219808/4986

**Comment by smonette** [comment]
Putting on hold until the /blog PR goes out, as that'll have the new Notice element.
