### ISSUE TITLE
Attachments show up for email despite not being attached

### ISSUE THREAD

**Issue by benborgers** [buttondown/roadmap#3078]
Reported here: https://secure.helpscout.net/conversation/2653965422/4941

Can reproduce on email `24f5ce74-6991-4f13-b5fe-d127b0f2325b`: 

![image](https://github.com/user-attachments/assets/37f736d9-31b3-4fbc-b706-6651afc8f9ab)

**Comment by jmduke** [comment]
Closed by https://github.com/buttondown/monorepo/commit/35344a093be8faba73df214673c3c298aef33e5f.
