### ISSUE TITLE
When choosing tags, the field extends past the modal window

### ISSUE THREAD

**Issue by dlwoda** [buttondown/roadmap#3093]
[Link to HelpScout](https://secure.helpscout.net/conversation/2661011724/5019?folderId=7228473)

User reported that when using tags feature to select email recipients, the field extends outside of the popup

![image](https://github.com/user-attachments/assets/9230794f-da62-4792-85f9-7834b12bfdf6)

**Comment by jmduke** [comment]
Fixed with The Drawer!
