### ISSUE TITLE
`List.Rows` with pills are _slightly_ vertically off center

### ISSUE THREAD

**Issue by jmduke** [buttondown/roadmap#3101]
<img width="1346" alt="image" src="https://github.com/user-attachments/assets/bfdb1380-1f2f-47d6-a1ed-df73f4930f8c">

**Comment by mary-ext** [comment]
oh we're being bit by what I call "Chrome's incorrect height calculation causing things to be off by 1px for some reason" issue
![image](https://github.com/user-attachments/assets/0308b4f2-4f3c-4e12-bbb4-6bc04faabd67)
