### ISSUE TITLE
Current OpenAPI spec is apparently invalid

### ISSUE THREAD

**Issue by jmduke** [buttondown/roadmap#3103]
Both https://oas-validation.com/ and https://apitools.dev/swagger-parser/online/ flag issues with GET `/v1/subscribers`

**Comment by jmduke** [comment]
@catdevnull This might be trivial, but since you're already poking around OpenAPI stuff I'm throwing this (and a couple related things) your way. If the validation errors are benign/silly, we can ignore them.

**Comment by catdevnull** [comment]
[apitools.dev/swagger-parser/online](https://apitools.dev/swagger-parser/online/) seems just plain wrong; it's complaining about perfectly valid "schema" fields. I believe it might not have implemented OpenAPI 3.1 properly, which changes that field a lot

[oas-validation.com](https://oas-validation.com/) seems to complain about recursion, but as far as I can tell, recursion is valid in OpenAPI schemas, it's just how that implementation decides not to recurse.

Am I missing something else?

**Comment by jmduke** [comment]
Nope, in that case we can close :)
