### ISSUE TITLE
Tooltips are overly sticky

### ISSUE THREAD

**Issue by jmduke** [buttondown/roadmap#3107]
It's not obvious to me why this happens, but it does, and it's bad (this is on a feed detail page):

![image](https://github.com/user-attachments/assets/bfa1dd06-079a-423e-9c0a-4572f13739d2)

It doesn't happen on _all_ instances, which makes me think there might be something weird with the specific rows, but at the very least we should singleton it so only a single tooltip can be present at a time?

**Comment by mary-ext** [comment]
Hmmm @jmduke can you still reproduce this on your end? I can't seem to repro on my end

**Comment by jmduke** [comment]
Nope.
