### ISSUE TITLE
Newsletter switching/selector broken on Android mobile

### ISSUE THREAD

**Issue by james-baker** [buttondown/roadmap#3114]
Repro:
Log in to Buttondown from a mobile, phone-type device.
Tap the Newsletter name in the very top-left to open the newsletter switcher.
See the newsletter switcher, everything looks mobile-layout-cooperative.
Tap on a newsletter name in the switcher.

Expected: Click-equivalent happens, Buttondown switches to working in/on that newsletter.
Actual: After tap, it looks like the on-hover state activates on that item in the switcher, but nothing else happens.

This completely blocked me from doing an operation with my phone last week, and I had to borrow a friend's laptop to do my task.

**Comment by jmduke** [comment]
@james-baker What phone/browser was it? I just tried on `demo.buttondown.email` and it appears to be switching correctly.

**Comment by james-baker** [comment]
Android, Chrome (a Pixel 8 phone). I'm gonna guess you're an iOS guy, given the existence of #2594 ;-)

Same broken behavior on demo.buttondown.email for me, so yeah seems OS-specific.

**Comment by jmduke** [comment]
@benborgers Throwing this on your end as you root-caused it

**Comment by james-baker** [comment]
Just noting that this is about the 4th time I've checked on this (i.e. could have used this ability, and have to route around by moving my work or arranging another device).

**Comment by jmduke** [comment]
@benborgers when you get the chance, mind dumping state here so @mary-ext can take a stab at it?

**Comment by benborgers** [comment]
I've been able to reproduce this issue where, on Android devices, clicking the hamburger menu to switch newsletters and then clicking a different newsletter doesn't change newsletters. It only seems to be consistently reproducible on physical Android devices, however it does reproduce on demo.buttondown.com in addition to buttondown.com. 

In Chrome dev tools it _sometimes_ reproduces when the mobile emulator is emulating an Android device (clicks are flaky and sometimes require a second click), but it isn't consistently reproducible like on a real physical Android device. 

<img src=https://github.com/user-attachments/assets/03acb1c9-f9e9-40a0-9859-d3a606dadeeb height=400 />

**Comment by mary-ext** [comment]
could be related to Draggable.js and Vaul not being compatible, let's disable the DnD sorting for now

**Comment by mary-ext** [comment]
Tried it out on my Android 14 device for a bit, interestingly, the only broken behavior I can observe is the broken draggable on drawers. I can switch between newsletters just fine.

**Comment by james-baker** [comment]
Works for me, thanks!
