### ISSUE TITLE
opening/editing any email showing HTML instead of Markdown in editor

### ISSUE THREAD

**Issue by james-baker** [buttondown/roadmap#3124]
Reopen for edit (or Reuse from a prior email to start a new email) an email.
(I'm in markdown editor mode, always am.)

Expected: Editor renders markdown
Actual: Editor renders HTML source and HTML entity escaping like
![image](https://github.com/user-attachments/assets/20d212bd-10d1-40a4-8449-99c4fef29d21)

Cycling the editor mode to Fancy and then back to Markdown does seem to work around the issue.

**Comment by jmduke** [comment]
@james-baker Mind giving this another go now?

**Comment by james-baker** [comment]
Looks fixed.

**Comment by james-baker** [comment]
This exact repro just happened to me again on email 8a1b606f-70bb-4908-844b-7573525edff2
I had just hard-refreshed immediately before doing "Reuse".

**Comment by james-baker** [comment]
And it didn't happen this week, no repro this time.
