### ISSUE TITLE
Single line breaks in markdown are not properly rendered

### ISSUE THREAD

**Issue by benborgers** [buttondown/roadmap#3135]
Markdown's standard stipulates that one single line break should not be rendered, only two or more should be rendered as a break between paragraphs. Our rendering pipeline recently started treating single line breaks as paragraph breaks, in contrast to the previous behavior. 

https://secure.helpscout.net/conversation/2663386411/5044/

**Comment by jmduke** [comment]
Closing as dupe of https://github.com/buttondown/roadmap/issues/3118.
