### ISSUE TITLE
Edit field persists for links when copying URL

### ISSUE THREAD

**Issue by dlwoda** [buttondown/roadmap#3146]
Link to [HelpScout](https://secure.helpscout.net/conversation/2663745462/5050?folderId=8083960) - includes behavior video

I've noticed that link pop-up basically persists if it's not closed with the X. I frequently copy URLs, and with the old link editor, I could select a link, copy it, and move on.

Now, though, the link box will follow me around the editor until it's manually closed. Not sure if this is a bug or just something to get used to

**Comment by jmduke** [comment]
Nah, this is a bug. Will fix!
