### ISSUE TITLE
Tag not being set on subscriber profile from form input selection

### ISSUE THREAD

**Issue by dlwoda** [buttondown/roadmap#3167]
While troubleshooting another issue, found that when using the select form input, a tag will be created and show on the subscriber profile under Metadata, but will not apply the tag to subscriber in the Tags area of profile

**Comment by jmduke** [comment]
@dlwoda Do you have a subscriber ID / email for this one?

**Comment by jmduke** [comment]
Closing in favor of #3185.

**Comment by dlwoda** [comment]
> @dlwoda Do you have a subscriber ID / email for this one?

Sorry! Missed notification :( weirdwriter [HS ticket](https://secure.helpscout.net/conversation/2666733341/5085?folderId=7228476)
