### ISSUE TITLE
Move dropdowns over to Radix Vue

### ISSUE THREAD

**Issue by mary-ext** [buttondown/roadmap#3171]
We've decided on using Radix Vue after some evaluations from https://github.com/buttondown/roadmap/issues/2983. While we could tackle nested dropdowns now, we're still unsure about how exactly that should work and look in conjunction with the drawer stuff that we need for mobile UI, so let's defer that for now.

[Dropdown Menu docs](https://www.radix-vue.com/components/dropdown-menu)
[Drawer thing for mobile](https://github.com/radix-vue/vaul-vue)

**Comment by mary-ext** [comment]
This might need a lot of work because I might need to untangle the List.Item stuff out of it, hopefully that pays off, it's a bit weird seeing different parts of the design system being mashed together

**Comment by jmduke** [comment]
> moving List.MenuItem to Dropdown.Item, which is a lot more clear.) I think we're better off doing that anyway

yeah this might be a good Step 1. From my cursory inspection there are no MenuItems that _aren't_ contained in a Dropdown anyway, so I suspect it's just carryover from back when the design system was a little more lawless
