### ISSUE TITLE
metadata tag not rendering data in preview render

### ISSUE THREAD

**Issue by james-baker** [buttondown/roadmap#3181]
I've had a {{ subscriber.metadata.firstname }} in many newsletters for a long time. This is a regression since last Friday.

Edit an email.
Add {{ subscriber.metadata.firstname }} or whatever equivalent to the (markdown, or fancy mode) editor.
Turn on the preview renderer.

Expected: A real firstname (the most recent subscriber, is what it has been in the past) is rendered.
Actual: Nothing is rendering there, which would usually mean "the most recent subscriber is lacking that metadata" but that's not true, their data hasn't changed since last week.

![image](https://github.com/user-attachments/assets/54228826-5fe1-4023-ad94-738fda4a1e4d)

**Comment by james-baker** [comment]
Took the risk and hit send - the metadata still showed up in my actual delivered email. (confirming it's a renderer problem)

**Comment by jmduke** [comment]
Fix should be live!
