### ISSUE TITLE
post-send checkbox no longer tied to analytics, creates conflicting UI state

### ISSUE THREAD

**Issue by james-baker** [buttondown/roadmap#3182]
![image](https://github.com/user-attachments/assets/3ffa7526-483f-4883-8d9f-21b07f4161ae)

When the data on the email changes to "status: sent" then the checkmark appears
But the numbers come from the Analytics request polling

Which are out of sync with the email status - sometimes just by a few seconds (So the other day I saw a checkmark next to "286/333" and wondered why there were so many delivery failures, before it updated again one final time to 332), and other times (when analytics fails, as it's doing today) it hangs there forever saying zero - even though I have a real email in my inbox, and I presume all deliveries actually worked.

**Comment by james-baker** [comment]
Oh - about 5 minutes after the emails went out, the analytics finally caught up today!

**Comment by jmduke** [comment]
Closing in favor of #2457, but will add some more flavor there!
