### ISSUE TITLE
Subscribe form errors on duplicate email

### ISSUE THREAD

**Issue by benborgers** [buttondown/roadmap#3242]
This error should be more tailored: 

![2024-08-10 at 20 35 58@2x](https://github.com/user-attachments/assets/c87d0dd7-6505-4846-98d1-e032b54f0b2e)

**Comment by catdevnull** [comment]
https://github.com/user-attachments/assets/e8771cd4-c90f-49cd-acac-e9d8d405c6d9



Hm, I'm not able to reproduce, what am I missing?

**Comment by benborgers** [comment]
Can't reproduce this anymore! Will close
