### ISSUE TITLE
Add some internal cross-links and FAQs to compete pages

### ISSUE THREAD

**Issue by jmduke** [buttondown/roadmap#3268]

**Comment by smonette** [comment]
Hey @jmduke! I'm grabbing this one for tomorrow, and wanted to get a few more details

To confirm:
- Compete pages are the "comparison" guides?
- For internal links, is there a preference between features, docs or a mix of both?

**Comment by jmduke** [comment]
- Not the guides, but the competitor pages (e.g. Buttondown vs. Mailchimp)
- Nope!

Specifically, I like the way [Bento](https://bentonow.com/vs/braze) just has some of the pricing / onboarding information embedded in the compete page as well.
