### ISSUE TITLE
Allow searching in history by substring

### ISSUE THREAD

**Issue by jmduke** [buttondown/roadmap#3271]
@catdevnull Throwing this your way since you just touched it so recently :)

I'm thinking just a simple textinput at the top of the history pane that does naive substring search?

**Comment by catdevnull** [comment]
Could you describe the use-case? Searching for a word you might've deleted? 

Should the search be done server-side or front-side?

**Comment by jmduke** [comment]
Yup, exactly. I think server-side is the way to go here; you can be pretty naive and pass it all the way to `generate_history.call` (and then filter `email.history.all`).
