### ISSUE TITLE
tags logic causing breaks on confirmation email

### ISSUE THREAD

**Issue by Ben-EvergreenS** [buttondown/roadmap#3274]
[Example email found here](https://secure.helpscout.net/conversation/2679942003/5256?folderId=7228473)

Users customizing with tags and variables experience space breaks in their confirmation emails.

Tested in admin in confirmation email and also have the same spaces.  Tested in the regular email area in markdown, but spacing was as expected.

Workaround:  delete extra spaces around tags, which doesn't allow spacing between lines.

**Comment by dlwoda** [comment]
additional context - author is using tags to create logic for message in Confirmation email.  There are additional line breaks being created anywhere there is a tag. Multi-line gap right after "Hi there 😊" text before next section of content

{% if subscriber.metadata.first_name %}

Hi there, {{ subscriber.metadata.first_name }}!

{% else %}

Hi there 😊

{% endif %}

{% if "source:klg" in subscriber.tags %}

**Comment by jmduke** [comment]
This spacing behavior is consistent with standard authoring:

<img width="1624" alt="image" src="https://github.com/user-attachments/assets/f6e6156a-aa8e-4970-8d0c-a5286dc6abc5">

As @Ben-EvergreenS mentions, if the author wants more fine-grained control here they can shift to Markdown mode:

<img width="1488" alt="image" src="https://github.com/user-attachments/assets/2807e000-1e16-4fa2-8356-fab17c73e0b2">
