### ISSUE TITLE
Creating code blocks in fancy mode requires an additional Enter key to work

### ISSUE THREAD

**Issue by mary-ext** [buttondown/roadmap#3337]
Noticed this while upgrading Tiptap packages in https://github.com/buttondown/monorepo/pull/1728, it happens on live prod so it's definitely not specific to the upgrades.

The code block is created successfully, but it's not possible to insert any text. The only workaround is to switch to Markdown mode and create a code block from there. From what I've observed, pressing Backspace with an "empty" code block would produce this result as well.

![image](https://github.com/user-attachments/assets/c664fc70-47ba-4c31-824e-678b792ed1d0)

**Comment by mary-ext** [comment]
pressing Enter key again seems to fix it, but it definitely shouldn't be happening in the first place.

**Comment by jmduke** [comment]
@mary-ext This was probably my fault. Can you try reverting https://github.com/buttondown/monorepo/commit/999c1dd4f986ff3b9fba73f62941d15dd9ee83fa and seeing if that fixes it?

**Comment by mary-ext** [comment]
Oops. That wasn't intended.

**Comment by mary-ext** [comment]
Tested this again and this seems to miraculously work again. Perhaps hotkeys-js was interfering with it? Who knows.
