### ISSUE TITLE
 Email dates on list page do not reflect newsletter selected location/region

### ISSUE THREAD

**Issue by Ben-EvergreenS** [buttondown/roadmap#3340]
[Link to Help Scout ](https://secure.helpscout.net/conversation/2691604947/5381?folderId=7228473)

"The email list is showing dates in US format (8/28/2024) even though my system region is set to Australia (28/8/2024)."

 Email dates on list page do not reflect newsletter selected location/region

**Comment by dlwoda** [comment]
my error is in understanding.  This is the date format not matching the UI for email list based on location.  This is a UI request to have the date format to match the location/region.  Let the author know this is a current UI limitation

**Comment by jmduke** [comment]
Closing as dupe of #1959!

**Comment by dlwoda** [comment]
> Closing as dupe of #1959!

Thank you! I think my GH search sometimes has too many words to find match 😂will update ticket
