### ISSUE TITLE
Move SVGs in big integrations list into standalone files

### ISSUE THREAD

**Issue by jmduke** [buttondown/roadmap#3341]
I started this work here: https://github.com/buttondown/monorepo/commit/3a83c1b7174fe4f6dcbaacb75e9286b0e17c8bd1

But there's another list of SVGs in `lib/integrations.tsx` that need the same treatment. Boring, I know, but should only take a few minutes.

**Comment by jmduke** [comment]
Actually, if while you're here you can also pull every single `sample` field into its own `mdoc` file — that'd also be great, just to make things a little more readable.

**Comment by catdevnull** [comment]
I'm not sure how to move the `sample` and `body` fields to separate files. The best I can think of is setting a `samplePath` in the integrations.tsx file, but then there's no click-to-definition. It doesn't seem to let me just add the `.mdoc` as an import.

**Comment by jmduke** [comment]
This probably should/could just be Keystatic-based, but I think splitting it into two separate items is reasonable
