### ISSUE TITLE
More JSON-LD woes

### ISSUE THREAD

**Issue by jmduke** [buttondown/roadmap#3343]
https://search.google.com/search-console/r/unknown-type/drilldown?resource_id=sc-domain:buttondown.com&item_key=CgIIHhADGA4&utm_source=wnc_10030322&utm_medium=gamma&utm_campaign=wnc_10030322&utm_content=msg_100058679&hl=en

**Comment by catdevnull** [comment]
again sounds like a good reason to #3308
