### ISSUE TITLE
When navigating the suggestions menu via down/up arrow, the selected item should always be visible

### ISSUE THREAD

**Issue by jmduke** [buttondown/roadmap#3352]

**Comment by mary-ext** [comment]
Should be fixed by https://github.com/buttondown/monorepo/pull/1533

https://github.com/buttondown/monorepo/commit/af5f2fd21cf0490c7d7f856b9c04beb163e8f14d#diff-172099cbe346033bffd748cc0d66ff483c9216e32b1f33f550c21e7bf6da3866
