### ISSUE TITLE
Bottom of finalization drawer is cut off on mobile devices

### ISSUE THREAD

**Issue by benborgers** [buttondown/roadmap#3361]
Probably the usual suspect of `vh` vs `svh/dvh/lvh` height units.

<img src=https://github.com/user-attachments/assets/9fd29bfd-c275-442a-a931-986102888b39 height=600 />

**Comment by jmduke** [comment]
@benborgers am I missing something obvious or is it not actually cut off?

**Comment by benborgers** [comment]
Oh I am extremely dumb - that screenshot is from me manually overscrolling and holding it up. If I let go it's cut off,.
