### ISSUE TITLE
PWA for Android always links to login page even in newsletter archives

### ISSUE THREAD

**Issue by jmduke** [buttondown/roadmap#3368]

**Comment by catdevnull** [comment]
Where am I supposed to put the route that generates the webmanifest? I tried putting it in `app/api/views/newsletters.py` but I have to go against the grain bypassing auth and other stuff as that's intended for authenticated users or API users

**Comment by jmduke** [comment]
Check out `emails.urls.base` as examples of how to wire up non-Ninja stuff into routing!
