### ISSUE TITLE
/stack is missing URLs for services

### ISSUE THREAD

**Issue by catdevnull** [buttondown/roadmap#3376]
we're using any types which makes this not be caught automatically.. psst: we could use zod to validate the sheet data when parsing it.

I don't have access to the google sheet to fix this.. so @benborgers

**Comment by jmduke** [comment]
Now you do! Assigned you the task :D 

1. please add it to /open-source while you're there...
2. I actually agree re: zod. It feels silly/unnecessary when it's validating our own API shape coming from Django but this makes sense

**Comment by catdevnull** [comment]
okay, i spent way too much time looking into this but basically:

- at some point we changed the formatting in the google sheets to have the url formatted in the name of the service itself
- opensheet doesn't support retrieving the URL embedded inside text. it could, using Google's `https://sheets.googleapis.com/v4/spreadsheets/${id}?key=${GOOGLE_API_KEY}&fields=sheets/data/rowData/values/hyperlink`, but it doesn't. 
- i think it makes the most sense to just modify the sheet to have the URL as a separate field
- i'm adding a comment to the sheet to make sure we don't delete that again!

**Comment by catdevnull** [comment]
quirk: i can't add a comment to the "generically" rendered sheets because they'll show up in the actual output site. I've added it to the ones that aren't generically rendered (stack and open-source)
