### ISSUE TITLE
Raindrop and Pocket both fail to save articles

### ISSUE THREAD

**Issue by jmduke** [buttondown/roadmap#3388]
Back in 2020 this was solved (at least for Pocket) by adding a div with the explicit data-prop of `itemprop="articleBody"`. This no longer works.

**Comment by catdevnull** [comment]
Do we have testing accounts?

**Comment by catdevnull** [comment]
I can't seem to reproduce with either Raindrop or Pocket with a standard newsletter.buttondown.com entry

Raindrop:


<img width="1026" alt="Screenshot 2024-09-12 at 11 21 31 AM" src="https://github.com/user-attachments/assets/1f280a70-10dd-41b6-83c8-4b50a6a371e3">


Pocket:

<img width="1018" alt="Screenshot 2024-09-12 at 11 20 57 AM" src="https://github.com/user-attachments/assets/64f73905-fecc-4ac9-bb2b-cc60b265f755">

**Comment by jmduke** [comment]
Poked the reporter: https://mastodon.social/@bixfrankonis@social.lol/113086048240800136

**Comment by jmduke** [comment]
https://mastodon.social/@bixfrankonis@social.lol/113126707166733801

**Comment by catdevnull** [comment]
sent an email to Raindrop from engineering@, waiting on a response

**Comment by catdevnull** [comment]
got back to us saying they've fixed it but I can still reproduce, so I replied to them

**Comment by catdevnull** [comment]
<img width="784" alt="Screenshot 2024-09-16 at 1 50 58 PM" src="https://github.com/user-attachments/assets/c4f43c9e-7a4a-4f21-9276-4f585b2b3efd">

fixed! can you reply to the user on Mastodon? @jmduke
