### ISSUE TITLE
CORS Errors with RSS/Forms

### ISSUE THREAD

**Issue by Ben-EvergreenS** [buttondown/roadmap#3394]
[Link to ticket](https://secure.helpscout.net/conversation/2699953104/5478?folderId=7228473)
[Link to ticket](https://secure.helpscout.net/conversation/2699982114/5479?folderId=7228473)

Users report CORS errors when using RSS to embed a preview on their own site or with submission forms.

**Comment by jmduke** [comment]
it me! 

(we should still properly pass CORS to the new domain, but glad that did resolve it.)
