### ISSUE TITLE
Command-Z doesn't work if preview pane is open

### ISSUE THREAD

**Issue by jmduke** [buttondown/roadmap#3396]
> Found a way to reproduce. When Preview is visible, the undo breaks. If I open and close another tab, and then go back to editing the email, the browser will perform the tab undo operation. If there was no other tab, the undo just doesn’t work.

**Comment by mary-ext** [comment]
Wonder if this will be fixed with the changes from the Tiptap editor refactor, let's merge that separately.

**Comment by mary-ext** [comment]
Closing this one because I don't think this has been an issue for me
