### ISSUE TITLE
Send warning email for Payment Links without `customer_creation = "always"`

### ISSUE THREAD

**Issue by benborgers** [buttondown/roadmap#3423]
If there are Stripe Payment Links on an account without `customer_creation = "always"` set, which point to a Buttondown-linked PWYW product, we should send a warning email to the customer. If these payment links are used, they won't work.

**Comment by jmduke** [comment]
Closing as dupe of #3360.

**Comment by benborgers** [comment]
not again

![image](https://github.com/user-attachments/assets/aa2c3b32-d50a-41d6-8e18-8f588bb4e7e8)
