### ISSUE TITLE
Premium saved as Public

### ISSUE THREAD

**Issue by Ben-EvergreenS** [buttondown/roadmap#3437]
[Link to Ticket](https://secure.helpscout.net/conversation/2704020719/5527?folderId=7228473)
[Link to Ticket](https://secure.helpscout.net/conversation/2699727649/5473/)

User marks emails to go out as Premium, but when they set them to schedule/finalize the email, they show as Public. Workaround is to adjust it after the change and it goes out as expected.

**Comment by jmduke** [comment]
Closing as dupe of #3404.
