### ISSUE TITLE
Code blocks in fancy mode editor doesn't work until you press enter once

### ISSUE THREAD

**Issue by benborgers** [buttondown/roadmap#3440]
https://github.com/user-attachments/assets/6a30da95-b279-4d3b-9594-4330909d9149

**Comment by mary-ext** [comment]
re: https://github.com/buttondown/roadmap/issues/3337
Somehow the issue has fixed itself, the code block styling *still* looks wrong but it no longer requires pressing Enter key to get it into a "fixed" state

**Comment by mary-ext** [comment]
Ohhh, now I know why I thought it was fixed, I was testing it on a different browser.

Chrome 128.0.6613.120: can reproduce
Firefox 132.0a1 (2024-09-11): cannot reproduce
