### ISSUE TITLE
Arbitrary buttons, not just the subscribe/upgrade ones

### ISSUE THREAD

**Issue by mary-ext** [buttondown/roadmap#3446]

**Comment by mary-ext** [comment]
@jmduke should we convert subscribe and upgrade buttons to a single customizable button? in the UI we could still offer the options to insert either buttons, it'd be wired to insert a predefined URL.

**Comment by jmduke** [comment]
Yup, I think that totally makes sense. and IIRC the subscribe button is just flatly better in the archive than the other one, so if we can standardize on that...
