### ISSUE TITLE
Release Zapier 1.8.x

### ISSUE THREAD

**Issue by catdevnull** [buttondown/roadmap#3459]
related to #3068 

after this -> https://github.com/buttondown/content-roadmap/issues/60

1.8.0 is already uploaded to Zapier, but it reports that the migration of Subscriber trigger/create/search into a resource seems to have turned it into a breaking change:

<img width="411" alt="Screenshot 2024-09-16 at 1 56 22 PM" src="https://github.com/user-attachments/assets/1d8ba5b3-3eb7-4fd0-89f1-5c6492f23a66">

I created a support ticket to see how to solve this. Worst case scenario, I have to turn them back into separate triggers/create/search.

I guess this means we have to release a 1.8.1, unless Zapier allows overwriting existing versions.

**Comment by jmduke** [comment]
I think (but am not sure) you can re-upload packages as long as they're not released. If that's not the case though, still not a big deal and feel free to bump to 1.8.1

**Comment by catdevnull** [comment]
> [redacted] here from Zapier's Platform Support team, happy to jump in on this.
>  
> Migrating a standalone trigger/create to a resource would constitute a breaking change because the key of the trigger/create would be different in the resource.
>  
> For example, if the key of a standalone "New Lead" trigger is new_lead, a resource with the key of lead would have trigger's key automatically as leadList which is different from new_lead. And this would constitute a breaking change.
>  
> As seen below, the keys for a resource's trigger, search, and create are generated automatically:
> 
> ![image](https://github.com/user-attachments/assets/e31cf0e4-82ce-4efe-8aac-110381c5f3e5)
>  
> That screenshot was taken from this section: [Resources](https://github.com/zapier/zapier-platform/blob/main/packages/cli/README.md#resources)
>  
> Having said that, you would have to keep using the standalone creates/triggers and only use resources to add new triggers or actions to this current integration.
>  
> I hope that helps.

I will revert the resource change and try to push a new 1.8.0

**Comment by catdevnull** [comment]
released!
