### ISSUE TITLE
Replace all outright subscriber deletions with gravestoning

### ISSUE THREAD

**Issue by jmduke** [buttondown/roadmap#346]

**Comment by ifpingram** [comment]
OT: What's gravestoning in tech speak? Not familiar with this term. Is it like a soft-delete? Thanks!

**Comment by jmduke** [comment]
Yup, exactly — slightly different than a soft delete (or at least in my parlance!) Soft delete implies that all of the data is still there, but just hidden; gravestoning implies that you keep certain elements of the data (such as IDs) for historical records, while removing PII such as emails

**Comment by ifpingram** [comment]
Got you - thanks. That makes good sense.
