### ISSUE TITLE
When "Hide from Archives?" is enabled, remove link to archive page from newsletter footer

### ISSUE THREAD

**Issue by smonette** [buttondown/roadmap#3490]
## Repro steps
- Have a newsletter with Archives enabled
- Write a newsletter
- Open send panel and enable "Hide from Archives?" 
- Send the email

## Current behavior
A link to the email in archives appears in the footer, and leads to newsletter. The email does not appear in the archive list though.

![Testing the hide from archives flow](https://github.com/user-attachments/assets/76a132dc-a708-4292-bd0d-efc828128754)

Here's [a test email](https://buttondown.com/nightcheese/archive/testings-the-hide-from-archives-flow/) I sent to repro 

## Expected Behavior
When this setting is enabled, the link in the footer would be removed (same as when Archives are disabled entirely)

****

This was reported by rasterisk via Discord.

![image](https://github.com/user-attachments/assets/d3bf43f4-291f-4e01-9c9a-db1f775e2cbc)

**Comment by mary-ext** [comment]
Ah, this is with the classic design
