### ISSUE TITLE
Custom CSS won't save: server error

### ISSUE THREAD

**Issue by brtholomy** [buttondown/roadmap#3498]
Tested on Firefox and Vivaldi on Linux, Chrome and Firefox on MacOS.

Incognito mode, all extensions off. Just won't accept any CSS. Custom footer field works.

![screenshot_20240929_1224](https://github.com/user-attachments/assets/54c06567-70a3-4199-9a1b-f14c62461ab3)

**Comment by jmduke** [comment]
Fix going live rn for this!

**Comment by brtholomy** [comment]
thank you
