### ISSUE TITLE
Allow styling text within a blockquote

### ISSUE THREAD

**Issue by jmduke** [buttondown/roadmap#3507]
cc @krangor

**Comment by mary-ext** [comment]
Assuming the issue is more about the editor having styling that doesn't really mesh well, as we do have formatting on the blockquotes.

**Comment by krangor** [comment]
Meaning in Markdown? As the Fancy editor does not seem to be able to style the text.On Oct 15, 2024, at 11:42 PM, Mary ***@***.***> wrote:﻿
Assuming the issue is more about the editor having styling that doesn't really mesh well, as we do have formatting on the blockquotes.
