### ISSUE TITLE
Strip `buttondown-editor-mode` comment from the beginning of plaintext emails

### ISSUE THREAD

**Issue by benborgers** [buttondown/roadmap#3534]
For newsletters with the plaintext hidden setting turned on, the `<!-- buttondown-editor-mode: * -->` comment is still included in the body. 

https://discord.com/channels/1044735046919127160/1058820708215566438/1291358839668604959

**Comment by Ben-EvergreenS** [comment]
[Linking Ticket](https://secure.helpscout.net/conversation/2738973691/5930?folderId=7228473) 

Describes the same issue Ben posted.
