### ISSUE TITLE
Scheduled email validation is not working without am/pm selector

### ISSUE THREAD

**Issue by jmduke** [buttondown/roadmap#3538]
<img width="503" alt="image" src="https://github.com/user-attachments/assets/2878b378-0914-4cfc-a15a-f6eed80d870c">

This should be showing a warning callout and disable the `finalize` input because it's in the past, but it doesn't... because the time isn't complete =(

<img width="495" alt="image" src="https://github.com/user-attachments/assets/41fcf83a-ac21-4fdf-adac-9425b8c779f3">

cc @hynek

**Comment by mary-ext** [comment]
Need to see if we can do anything about it because `<input>` isn't giving us any info until the date/time is complete

**Comment by mary-ext** [comment]
Ooh, perhaps we can assume the time for the purposes of validation if the time isn't set yet?

**Comment by mary-ext** [comment]
Hrm... the only good way might just be to hoist the separated inputs upwards...
