### ISSUE TITLE
Better mobile/tablet expansion behavior for preview

### ISSUE THREAD

**Issue by jmduke** [buttondown/roadmap#3542]
When in preview mode on tablet, we don't actually show the expanded view by default:

<img width="854" alt="image" src="https://github.com/user-attachments/assets/0c26fad2-846a-4572-af0f-ace5445dfa92">

Until someone clicks the expand button:

<img width="854" alt="image" src="https://github.com/user-attachments/assets/62c27490-6640-4a3f-905b-05701f3e90f2">

This behavior feels kind of weird to me. I was gonna suggest unifying the two but maybe we just hide the expand button/view entirely for non-desktop viewports?

**Comment by mary-ext** [comment]
Hrmmm, it might be good if we just wire tablet/mobile users directly to that preview dialog, let's see if we can add a media query for it
