### ISSUE TITLE
Give `custom-email-template` the full-page / Naked treatment

### ISSUE THREAD

**Issue by jmduke** [buttondown/roadmap#3552]
We have a hidden setting (`custom_email_template`) that we flag folks into which lets them to change everything about the backing template:

![image](https://github.com/user-attachments/assets/b0e69729-1dc1-4a45-86c8-464ff959443d)

This is not really pleasant to work with: it's just an HTML-flavored codemirror blob.

Instead, we should surface this at `/settings/design/email-template` and have basically identical UX to naked mode, like we do with some of the other text areas (though unlike, say, `/settings/design/header`, we shouldn't let folks swap between Fancy and Markdown — we can just always assume Naked)

**Comment by mary-ext** [comment]
I think we should just dupe the DraftPage component for now as this is a one-off
