### ISSUE TITLE
Customize dropdown can't be navigated via keyboard

### ISSUE THREAD

**Issue by mary-ext** [buttondown/roadmap#3574]
We'd have to switch this for a Popover, the keyboard focus for `<DropdownMenu>` only functions for `<DropdownMenuItem>`

Alternatively, we can consider not using checkboxes here.

**Comment by jmduke** [comment]
Presumably the same problem exists for the other `customize` dropdowns (/emails, /subscribers)? So long as whatever we go with is consistent across all of them, I'm fairly agnostic
