### ISSUE TITLE
Emoji are stripped from auto-generated share image

### ISSUE THREAD

**Issue by chriskrycho** [buttondown/roadmap#3588]
Here is an example image from [my latest newsletter issue](https://newsletter.music.chriskrycho.com/archive/october-2024-the-rhythm-of-the-work/):

![generated](https://github.com/user-attachments/assets/fc87d148-6d7d-4f9c-b9c5-e5fbda4dfd8e)

The title for the item was:

> 🎼 October 2024: The Rhythm of the Work

Notice that the 🎼 emoji was removed, but the space for it remains, so the resulting image looks weirdly imbalanced!

**Comment by jmduke** [comment]
Dupe of #3363!

**Comment by chriskrycho** [comment]
Doh, I missed it by way of a too-specific search. Thanks!
