### ISSUE TITLE
Mobile login blank page "You used this last time"

### ISSUE THREAD

**Issue by Ben-EvergreenS** [buttondown/roadmap#3590]
[Link to Ticket](https://secure.helpscout.net/conversation/2754576521/6160?folderId=8083960)

Users on mobile when trying to login to Buttondown cannot. Clicking on the login link leads to a white page with no way to login and only a message You used this last time. Confirmed on my own device with Firefox.  This issue doesn't appear on PC browser. 

![image](https://github.com/user-attachments/assets/36209d2f-3b8d-4fb2-93e3-2ec56756cf0f)

**Comment by dlwoda** [comment]
behavior confirmed on Android Chrome - changing to Desktop Site view is workaround

**Comment by dlwoda** [comment]
@benborgers confirming this is fixed on Android and Apple - can be marked resolved
