### ISSUE TITLE
Zapier says `{{ name }}` rather than referring to the name of the connected application

### ISSUE THREAD

**Issue by jmduke** [buttondown/roadmap#36]

**Comment by catdevnull** [comment]
are there repro instructions for this? I haven't tried it yet but I also haven't seen it happen

**Comment by jmduke** [comment]
@catdevnull Go through the auth process (like create a Zapier account and plug in an API key of your own from Buttondown.) You should be able to see it then!

**Comment by catdevnull** [comment]
I did a basic flow of signing up, creating a zap with triggers and actions, but I can't seem to reproduce this at all :|

**Comment by jmduke** [comment]
hey, that's great! means we can close it :)
