### ISSUE TITLE
ergonomics/UX of setting up sending from a custom domain

### ISSUE THREAD

**Issue by james-baker** [buttondown/roadmap#759]
Hey Justin, thought I'd capture some thoughts and soft wishes from my process of finally setting up my Buttondown newsletters to send from my own domain.

Should I be using a subdomain(s) or the root domain for my newsletters?
Did some background net reading, found some stuff about domain reputation but no hard technical constraints. The "Dreamhost" guide page (it's the only one, why is it labeled as Dreamhost-specific?) has an example of "buttondown.xyz" (so, root) but the other page uses and "newsletter.this-week-in-poetry.com" and "mail.janedoe.com" examples. I could have used a default recommendation/mention, even if it's "do whatever you feel like."

Will Buttondown need separate DNS for each newsletter?
Answer from trying: No, if I'm using the same domain for multiple newsletters then the DNS records only need to be done once.

https://docs.buttondown.email/sending-domains/sending-from-dreamhost
* Can/should this page say something about SPF?
* Does "Your Email address must match your custom sending domain." apply to subdomains too? I still don't know

https://docs.buttondown.email/getting-started/sending-from-a-custom-domain
* This page talks about combining the SPF record, but I wasn't "asked" to set up an SPF record. What would have been asking me to? Huh, seems like something I should have regardless?
* It references "include:mailgun.org" - should I just add exactly that to my SPF list? I guess I'll try it.

The technical implementation of "Click here" to get DNS records and "Check DNS" was pretty good. It was a little tricky to copy the long strings out of the squished table, but no big deal. I briefly looked for a "Done" type button after the DNS was good, before going to the X button in the top-right. Then... I hit "Update Settings" again, just to be sure everything stuck firm, haha.

**Comment by jmduke** [comment]
This is great feedback, and agreed that it's mostly documentation that is key here (and I think I have a few other specific issues floating around that touch on what you're hitting here.)

**Comment by jmduke** [comment]
Folding this into #1139.
