### ISSUE TITLE
See which unconfirmed users have already been reminded

### ISSUE THREAD

**Issue by jyavorska** [buttondown/roadmap#776]
It would be helpful in the unconfirmed subscriber list to show who I've already sent a reminder to, so I don't do it more than once.

Relates to https://github.com/buttondown-email/roadmap/issues/692 in that, as long as I'm doing that manually, I don't want to accidentally annoy people.

**Comment by jmduke** [comment]
Totally makes sense. (There's some logic on the backend that does this, but I should make it more explicit.)
