### ISSUE TITLE
Better preview emailing

### ISSUE THREAD

**Issue by jmduke** [buttondown/roadmap#792]
Let's take the `DraftRecipientsModal` and apply it to a bunch of places, so it's always easy to test sending an email to an arbitrary subscriber!

## Locations

- [ ] Custom teasers
- [ ] Sending domain modal
- [ ] Automation emails
- [ ] RSS
- [ ] Confirmation email

**Comment by efletch** [comment]
+1 for confirmation email preview[*](https://secure.helpscout.net/conversation/2599350955/4299)

**Comment by jmduke** [comment]
This is going to get folded into the workstream outline in #263.
