### ISSUE TITLE
Omnibus: more subscriber filters

### ISSUE THREAD

**Issue by martindufort** [buttondown/roadmap#83]
- [x] Subscriber import
- [ ] Clicks/opens on specific emails
- [ ] _Negative_ filtering
- [ ] Survey answers

**Comment by jmduke** [comment]
Yup, totally makes sense.

**Comment by jmduke** [comment]
A couple things here:

1. Multiple tags
2. Creation date

**Comment by jmduke** [comment]
As mentioned in #221:

```
folks who are unconfirmed but have not been sent a reminder email
folks who clicked on a link in Email X
```

**Comment by jmduke** [comment]
We've done all of these, and the ones that don't exist can be handled from outside the core Subscribers list!

**Comment by jmduke** [comment]
Oh, except surveys. Reopening for surveys.
