### ISSUE TITLE
Allow audio embedding like images

### ISSUE THREAD

**Issue by jmduke** [buttondown/roadmap#840]
For now, folks interested in this may want to avail themselves of our [Soundcloud integration](https://buttondown.email/features/integrations/soundcloud)

**Comment by chriskrycho** [comment]
Note: your docs for this are not updated, and still links to this issue! 😅

Also, general-purpose audio embeds which support something like the “listen to this as a podcast” _a la_ Substack might be a nice v2 of this feature.
