### ISSUE TITLE
grab bag of feedback on drafts/emails update

### ISSUE THREAD

**Issue by james-baker** [buttondown/roadmap#872]
I notice some new feature work landing, probably with some refactoring turning drafts into more normal emails etc. I like the new "Filter" widget, though I won't need to use it. I did go looking for the old "Drafts" page in the main nav, but then I'm glad it's gone ultimately.

ux: I have some mixed feelings (thought net positive) about the UI for drafts being so integrated with published emails. When I went to delete a draft, I felt the urge to triple-check that I wasn't deleting a published email (since that is now possible, and the warning is scarier). Oh, maybe I could learn to filter down to drafts, then be less scared about mis-selecting. (But maybe the warning message could be customized for drafts, because they aren't already published so the warning is a little misleading.)

default sort: I prefer "-date" as default, so I see recent emails first instead of the oldest emails I ever sent. I also noticed this change on the subscribers page a little while ago - /subscribers now ends up as /subscribers?order=date&filter=&page=1 and I'd really rather have -date there too

deleting drafts: I deleted a spurious draft, and all that changed (after the toast) was that the status went from "draft" to "deleted". That's great as a mistake-fixing/recycle-bin feature, but then I noticed that I did want it to go away and not linger forever. I saw that the item's context menu still offered "Delete" despite already being in that state, so I tried it again and then it did disappear. If that's the intended flow, cool, maybe the context menu item could say "Delete permanently" to clear up any confusion.

spurious drafts: Oh yeah, I should mention why this exists. I'll make a new case if/when I solidify the repro, but if I Reuse an old mail (and then change the title of it?), I seem to end up with an extra draft hanging around after I finish editing and sending the email. The last spurious draft had a half-changed title - does changing the title of a draft create a new one?

polish: I noticed https://buttondown.email/archive gives a 404 currently. Might have been nice to 301/308 that to /emails, but maybe that ship has already sailed.

**Comment by jmduke** [comment]
SMH, you beat me to even publishing the blog post about it :) 

Coalescing a couple obvious things:

- [ ] Swap the default date for sorting
- [ ] Tweak copy on 'permanent deletion' flow
- [ ] Add a redirect from `/archive` for now

This draft deletion flow bit is definitely interesting for me though. So reusing a previous email and tweaking the title creates a second draft on your end?

**Comment by james-baker** [comment]
Oh yeah this one-extra draft thing happened to me again this week.
![image](https://user-images.githubusercontent.com/89615/193505651-9527823d-db68-4750-a259-cdcbe0d79d6e.png)
The draft once again has a partially-edited title, which seems significant.

**Comment by jmduke** [comment]
Excellent, t/y. (To make sure I understand — the draft was a leftover from the email that got sent out correctly. Do you mind emailing me or commenting with the subject?)

**Comment by james-baker** [comment]
Sure, it's not sensitive.
The email that was sent out correctly, nothing abnormal-seeming about the experience, was: "IS Calendar 8.1 Oct 2-8 — Season 8 Launch, Circling, House Party"
The spurious draft was titled: "IS Calendar 8.1 — Season Wrap-up"
and finally, the prior email that was reused was titled "IS Calendar 9/18 Week 7.11 — Season Wrap-up"
